### ISSUE TITLE
 @JsonScalaEnumeration support with secondary constructor

### ISSUE THREAD

**Issue by crumbpicker** [FasterXML/jackson-module-scala#108]
While testing to port Jacks (https://github.com/wg/jacks) example to the Jackson's Scala Module I have encountered an issue with deserialization using secondary constructor containing an enumeration.

It seems that the @JsonScalaEnumeration annotation is ignored because I obtain the following JSON string:
{"foo":"bar","bar":1,"v":"A","ed":{"enumClass":"fr.proline.module.exporter.msi.Editor","value":"emacs"}}
While it should be:
{"foo":"bar","bar":1,"v":"A","ed":"emacs"}

Here is the Jacks example case class definition (KitchenSink) I'm tyring to work with:

```
sealed trait AB { @JsonValue def jsonValue: String }
case object A extends AB { def jsonValue = "A" }
case object B extends AB { def jsonValue = "B" }

class EditorType extends TypeReference[Editor.type]
object Editor extends Enumeration {
  val vi, emacs = Value
}

case class KitchenSink[T] @JsonIgnore() (
  foo: String,
  bar: T,
  v: AB,
  ed: Editor.Value
) {

  @JsonCreator
  def this(
    @JsonProperty("foo") foo: String,
    @JsonProperty("bar") bar: T,
    @JsonProperty("v")   v: String = "A",
    @JsonProperty("ed") @JsonScalaEnumeration(classOf[EditorType]) ed: Editor.Value = Editor.emacs
  ) = this(foo,bar,if (v == "A") A else B, ed )

}
```

**Comment by jccode** [comment]
I'm sorry that I wonder that does the expected result `{"foo":"bar","bar":1,"v":"A","ed":"emacs"}` works or not ?  I search all the posts about this issue, and I found most of the answers pointing to below link: https://github.com/FasterXML/jackson-module-scala/wiki/Enumerations .

I test the codes describe in the wiki, I found the deserialized json string still contains "enumClass". 

Test codes:

    val mapper = new ObjectMapper()
    mapper.registerModule(DefaultScalaModule)

    def serialize(value: Any): String = {
      import java.io.StringWriter
      val writer = new StringWriter()
      mapper.writeValue(writer, value)
      writer.toString
    }

    object Weekday extends Enumeration {
      type Weekday = Value
      val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
    }
    class WeekdayType extends TypeReference[Weekday.type]
    case class WeekdayHolder(@JsonScalaEnumeration(classOf[WeekdayType]) weekday: Weekday.Weekday)
    serialize(WeekdayHolder(Weekday.Mon))
    // output:
    // res2: String = {"weekday":{"enumClass":"A$A152$A$A152$Weekday","value":"Mon"}}


While the output is

    res2: String = {"weekday":{"enumClass":"A$A152$A$A152$Weekday","value":"Mon"}}


Am I make any mistake? Is it possible to get the output as: ` {"weekday":"Mon"}`  . And how?  Any explanation would be appreciate.

**Comment by david-bouyssie** [comment]
On my system (jackson 2.8.9) I have this:

```{"weekday":"Mon"}```

What is your version of Jackson?

**Comment by jccode** [comment]
<scala.version>2.12.4</scala.version>
     <jackson.version>2.8.10</jackson.version>


I try the scala 2.12.2 + jackson 2.8.9, still not works.  Would you please provide me a minimum working project / snippets for testing on my system?  Thanks very much.

**Comment by david-bouyssie** [comment]
I'm using Scala 2.11.11 but I don't think it could explain the difference of behavior.
Could you please share the entire .scala file you use for testing?

**Comment by jccode** [comment]
I'm sorry, It's my fault. The previous test code snippet I written  down in the IntelijIDEA "Scala worksheet" file, which give me the incorrect result 

    {"weekday":{"enumClass":"A$A152$A$A152$Weekday","value":"Mon"}}`

@david-bouyssie As you ask me to provide the .scala file, I write the sample code in a scala file. It turns out the final result is as expected. Thanks for you tips.

**Comment by david-bouyssie** [comment]
I think it maybe a class scoping issue.
I guess that the class WeekdayHolder and the case class WeekdayHolder must be defined in a different scope/package than the "main" code (call of serialize).
