### ISSUE TITLE
@transient annotation seems to be ignored

### ISSUE THREAD

**Issue by crumbpicker** [FasterXML/jackson-module-scala#109]
The scala builtin @transient annotation seems to be ignored.
@JsonIgnore does the job but the standard @transient annotation should produce a similar result isn't it ?

**Comment by JohnTheBeloved** [comment]
Please, what is the status of this issue as I need this too....and urgently, Thanks

**Comment by christophercurrie** [comment]
The underlying issue FasterXML/jackson-databind#296 has not yet been addressed. If you need it urgently I would recommend looking into creating a PR for the databind project.

**Comment by cowtowncoder** [comment]
FWTW, https://github.com/FasterXML/jackson-databind/issues/296 was implemented for Jackson 2.6 and is now available.

**Comment by nbauernfeind** [comment]
It appears that no other changes were needed to the Scala module. I've added a regression test, but will otherwise close this issue.
