### ISSUE TITLE
@JsonCreator and companion object

### ISSUE THREAD

**Issue by crumbpicker** [FasterXML/jackson-module-scala#110]
I have a question related to the @JsonCreator annotation. The Jacks library allows to use this annotation in combination with the companion object of the case class to be deserialized. It has the benefit to be less obstrusive than defining a secondary constructor in the case class. My problem is that it is sometimes hard to deal with multiple constructors having default values.

So is it possible with the scala module to use the @JsonCreator annotation in the companion object ?

**Comment by pjfanning** [comment]
There are test cases in latest versions of jackson-module-scala that use `@JsonCreator` annotations on companion object functions. Please reopen if you have a specific test case that does not work.
