### ISSUE TITLE
2.3 deserializes to immutable maps

### ISSUE THREAD

**Issue by lukepalmer** [FasterXML/jackson-module-scala#128]
In version 2.2, doing this on a multi-level JSON doc:

```
mapper.readValue(json,classOf[mutable.Map[String,Any]])
```

...would result in a mutable map of mutable maps.

In 2.3.1, you get a mutable map of **immutable** maps.  Is this intentional?  Any way to control behavior?

**Comment by jam01** [comment]
Hey all, sorry to poke an old issue but I'm having a hard time figuring this out and thought it may be cleaner than opening a new one. Basically I'm trying to make changes to the Map returned by readValue and it'd seem that the ATR approach posted by @lukepalmer is deprecated. I see the source code now points to TypeFactory but I'm not sure how to take that approach either.

How can I use TypeFactory to force jackson to return a mutable map? Is that the best way to do this? Or is there a straight forward way to recursively copy the map into a new mutable instance?

Thanks
