### ISSUE TITLE
readValue for Map[String, Any] or List[Any] is very slow

### ISSUE THREAD

**Issue by anantn** [FasterXML/jackson-module-scala#145]
Anytime there's a type that contains 'Any', 'AnyRef' or '_', the scala module's performance is very slow.

Consider JSON of the form `["foo", "bar", "baz"]`. `objectMapper.readValue[List[_]](json)` is 10x slower than `objectMapper.readValue[List[String]](json)`.

This would be fine on its own, except in the cases where the JSON contains mixed types. What would be the optimal way to parse JSON that looks like the following?

```json
{
"test": [
  {
    "name": "foobar",
    "list": [
       {"type": "int"},
       {"type": "float"}
     ]
  }
]
}
```

**Comment by christophercurrie** [comment]
Closing this issue as resolved; reports have come in on a similar issue that performance has improved in 2.4.4. If this is not your experience, feel free to open a new issue.
