### ISSUE TITLE
Use type tags instead of manifests.

### ISSUE THREAD

**Issue by taylorleese** [FasterXML/jackson-module-scala#168]
Type tags should be used rather than manifests since manifests are planned to be deprecated. See http://docs.scala-lang.org/overviews/reflection/typetags-manifests.html.

> In Scala 2.10, scala.reflect.ClassManifests are deprecated, and it is planned to deprecate scala.reflect.Manifest in favor of TypeTags and ClassTags in an upcoming point release. Thus, it is advisable to migrate any Manifest-based APIs to use Tags.

**Comment by eugeniyk** [comment]
Is there any progress on this issue?

I have a problem with manifest and type erasure described here, not sure how to work around:
https://gitter.im/scala/scala?at=5fd0fa2f1f36292125def9a4

Full test: https://scastie.scala-lang.org/eugeniyk/MY5xh0SAS2uB5fG3xDhp2Q/5

**Comment by pjfanning** [comment]
ScalaObjectMapper is deprecated and unsupported for Scala 3 - ClassTagExtensions is it's replacement (jackson 2.13 is first release with a proper ClassTagExtensions implementation)
