### ISSUE TITLE
remove guava

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [FasterXML/jackson-module-scala#174]
**problem:**

we can not use ```jackson-module-scala``` with play2 and other things due to guava dependency.

#86 is closed, not sure why, the problem is still there.

**solutions:**

1) would it be sufficient to use simple map or soft reference map for type cache?

2) perhaps we could hide guava behind facade with pluggable implementation 
and make guava ```optional``` although default cache provider?

**Comment by christophercurrie** [comment]
5b36c6b removes guava as a dependency. This change will go out when I release version 2.5 of the Scala module, hopefully later this week.

**Comment by Andrei-Pozolotin** [comment]
thank you.
