### ISSUE TITLE
Deserializing to Option[T] doesn't properly handle json string values

### ISSUE THREAD

**Issue by c089** [FasterXML/jackson-module-scala#175]
I encountered an issue with deserializing JSON like this:

```json
{"x": "42", "y": "foo"}
```

Note the value of `x` is a valid integer, but represented as a JSON string, which is fairly common. Now, trying to deserialize this to `Int`s works as expected: `x` will be parsed as `Int`, and `y` will trigger an `InvalidFormatException`. However, if you try to serialize this as `Option[Int]`, it will succeed in both cases, and you get a reference to a `Some` that holds a `String`, which caused very subtle bugs in our code.

I wanted to do a pull request, but unfortunately I was not able to build this project from a clean checkout using sbt or IntelliJ, so instead I isolated [some tests](https://github.com/c089/jackson-module-scala-bugreport/blob/master/src/test/scala/com/polycodal/bugreport/com/fasterxml/jackson/module/scala/OptionalTypeSpec.scala) to an external [repository](https://github.com/c089/jackson-module-scala-bugreport). The last two tests there are failing.

If someone would be willing to help me build `jackson-module-scala` and/or pair with me on fixing this, jut ping me on twitter @c089.

**Comment by c089** [comment]
Ah yes that makes more sense, thanks. Maybe you could add that to `README.md` to make it a bit easier to get started :)

**Comment by christophercurrie** [comment]
Ok, so just a heads up, the tests as provided would not work, but that is not the cause of the issue. The issue in the provided tests is [the use of `classOf`](https://github.com/c089/jackson-module-scala-bugreport/blob/master/src/test/scala/com/polycodal/bugreport/com/fasterxml/jackson/module/scala/OptionalTypeSpec.scala#L26):

```scala
val result: Option[Int] = mapper.readValue(json, classOf[Option[Int]])
```

`classOf` discards any type information that might have been provided, returning the "erased" type, for which Jackson has to deduce the type parameter from the JSON text; no type conversion is done. The correct code for this uses the `TypeReference` type to retain the type parameter:

```scala
val result: Option[Int] = mapper.readValue(json, new TypeReference[Option[Int]]{})
```

However, this would not fix the underlying issue, which is the same as is reported in #104, and is described in more detail in the [FAQ](https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-and-other-primitive-challenges). As describe there, getting the correct behavior involves the use of the `@JsonDeserialize` annotation. If you have challenges using that annotation, please follow up on the [mailing list](https://groups.google.com/forum/#!forum/jackson-user).

**Comment by c089** [comment]
oh yes, that makes sense :) Thank for the explanation
