### ISSUE TITLE
Using Jersey 2.5.0, case classes fail to serialize

### ISSUE THREAD

**Issue by clamothe** [FasterXML/jackson-module-scala#179]
Using either 2.4.4 or 2.5.0-SNAPSHOT with otherwise all 2.5.0 Jersey components results in an exception when serializing a case class instance:
com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'someField' (in class [a scala case class])

I may be able to provide a sample tomorrow if useful.

**Comment by christophercurrie** [comment]
Sorry for the delay following up. Jackson 2.5 had unfortunately backwards-incompatible changes, so I would not expect 2.4.x versions of the Scala module to work with it. However, the fact that the 2.5.0-SNAPSHOT version does not work either is disturbing. A sample, if you can provide one, would be extremely useful.

If possible, I would also like to know if using exclusively 2.4.4 components works for your use case; it may help in identifying where the regression lies.

**Comment by clamothe** [comment]
When I noticed this, I had just switched from 2.4.4 components to 2.5.0. That said, I can no longer reproduce this. I'll reopen if I can. Thanks!
