### ISSUE TITLE
jackson-module-scala 2.3.1 not published for scala 2.11

### ISSUE THREAD

**Issue by aniketbhatnagar** [FasterXML/jackson-module-scala#181]
Build for jackson-module-scala 2.3.1 is not published for 2.11. On of the reasons for depending on 2.3.1 version is because apache spark is transitively dependent on jackson-core:2.3.1. For scala 2.11 users, this is a bit of a pain. One possible workaround is do define the dependency as follows :

"com.fasterxml.jackson.module" % "jackson-module-scala_2.10" % "2.3.1" excludeAll(
  ExclusionRule(organization = "org.scala-lang"),
  ExclusionRule(organization = "org.scalatest")
) 

But it would be since to have 2.3.1 published.

**Comment by christophercurrie** [comment]
Unfortunately, this isn't possible, without a whole lot of headache. 2.3.x provided support for Scala 2.9, and 2.4 and later support Scala 2.11. The two versions of Scala are not 100% compile-time compatible (2.9 constructs that were deprecated in 2.10 were then removed in 2.11). The 2.3 branch remains open for critical bugs to support Scala 2.9 users (of which there are few), but users of Scala 2.11 are only supported in 2.4 and later.

Other options for dealing with this kind of dependency headache is to update the dependency in the framework, which I admit can be challenging and not always possible, or to hide your dependency on the later version with the use of Proguard or other obfuscation tools.

Sorry I can't be of more help.
