### ISSUE TITLE
How to serialize Scala getter value?

### ISSUE THREAD

**Issue by provegard** [FasterXML/jackson-module-scala#183]
I'm trying to understand how to serialize arbitrary none-case classes to JSON. In my unit tests, I use the following class:

```
class PropClass(private[this] val _foo: String) {
  def foo = _foo
}
```

My mapper is created like this:

```
val mapper = new ObjectMapper()
mapper.registerModule(DefaultScalaModule)
```

And I create JSON like this:

```
val writer = new StringWriter()
mapper.writeValue(writer, value)
```

But the value of `foo` doesn't appear in the JSON output. What would be the correct way of solving it, preferably without using annotations?

**Comment by christophercurrie** [comment]
Sorry you're having difficulty; I encourage you to use [the mailing list](https://groups.google.com/forum/#!forum/jackson-user) to ask questions, and reserve Github Issues for bug reports. I've answered this question in [this thread](https://groups.google.com/forum/#!topic/jackson-user/9dUySIw-ZvI), feel free to post follow-up questions there.
