### ISSUE TITLE
2.4.4 binary: JsonScalaEnumeration not compatible with java 6

### ISSUE THREAD

**Issue by ziIizeqQ** [FasterXML/jackson-module-scala#185]
java.lang.UnsupportedClassVersionError: com/fasterxml/jackson/module/scala/JsonScalaEnumeration : unsupported classversion 51.0

**Comment by flicken** [comment]
This issue appears versions 2.4.0 through .5,  2.5.0, 2.5.1-SNAPSHOT, and 2.6.0-SNAPSHOT.

However, it does not apply to 2.4.6-SNAPSHOT. 

This also applies to the ScalaModule class:
     $ file $(find . -name '*.class' ) | grep 51.0
    ./com/fasterxml/jackson/module/scala/JsonScalaEnumeration.class:                                                                                                      compiled Java class data, version 51.0
    ./com/fasterxml/jackson/module/scala/ScalaModule.class:                                                                                                               compiled Java class data, version 51.0

**Comment by flicken** [comment]
@christophercurrie Any possibility of getting a 2.4.6 release to fix this issue?

**Comment by christophercurrie** [comment]
My apologies this issue has gone unnoticed for so long. I'll cut new releases for the 2.3, 2.4, and 2.5 release series ASAP (hopefully tonight).

**Comment by christophercurrie** [comment]
New releases for 2.5.1 and (for alignment with upstream Jackson revisions) 2.4.5-1 are on their way to Maven central. 2.3.x releases do not have this issue, as that branch still enforced Java 1.6 class file output.

Thanks for reporting this one, and may apologies for the oversight.

**Comment by flicken** [comment]
Thanks for fixing!  I've verified that this is fixed in 2.4.5-1 for both 2.10 and 2.11 Scala versions.
