### ISSUE TITLE
Either type cannot be deserialized 

### ISSUE THREAD

**Issue by kgignatyev** [FasterXML/jackson-module-scala#204]
I have code that reproduces problem at:
https://github.com/kgignatyev/misc/tree/master/scala-databind-issue

serialization happens fine, but deserialization fails

{"contents":[{"l":"some string"},{"r":{"id":"a","cType":"widget"}}]}

class EitherHandlingSpec extends FunSuite {

  test("can handle 'either'") {
    val p = new ContentPage
    p.contents += Left("some string")
    p.contents += Right(ContentPointer("a","widget"))
    val ser =  McyObjectMapper.mapper.writeValueAsString(p)
    println("ser:\n\n"+ ser)

    val newPage = McyObjectMapper.mapper.readValue(ser, classOf[ContentPage])

    assert(newPage.contents.length==2)
  }

}

class ContentPage {
  var contents:ListBuffer[Either[String,ContentPointer]] = ListBuffer()
}

case class ContentPointer (var id:String, var cType:String )

**Comment by nbauernfeind** [comment]
A shorter example of the same issue:

```scala
object T extends App {
  val mapper = new ObjectMapper with ScalaObjectMapper
  mapper.registerModule(DefaultScalaModule)

  val ser = mapper.writeValueAsString(Seq(Left("left")))
  println("ser:\n\n"+ ser)

  val newPage = mapper.readValue[Seq[Either[String, String]]](ser)
}
```

The `EitherDeserializer.deserialize` is being invoked twice. The second time `jp.nextToken()` is `null` which yields to `key` being `null` and fails the match in method `deserializeEither`. I don't know under what conditions this method is invoked, but it seems to think that there is another element in the Seq even though there isn't.

Note that deserializing a Left or a Right not wrapped in a Seq works fine.

**Comment by nbauernfeind** [comment]
This was fixed in https://github.com/FasterXML/jackson-module-scala/commit/78882ed7ea08fd3e8e9d0dcba40e1b1c72a76898 and has a regression test.
