### ISSUE TITLE
Scala-library and Scala-reflect versions in 2.11:2.5.2

### ISSUE THREAD

**Issue by philipmeadows** [FasterXML/jackson-module-scala#206]
In jackson-module-scala 2.11:2.5.2 it brings in dependencies on scala-library and scala-reflect versions 2.11.4.

Should this be 2.11.6?

**Comment by christophercurrie** [comment]
I generally don't update the scala-library dependencies for patch releases, as it's trivial to override them if you need to. But I'll update the version for 2.6.

**Comment by philipmeadows** [comment]
Great thanks.
