### ISSUE TITLE
Deserialization of case object creates a new instance of case object

### ISSUE THREAD

**Issue by wsowa** [FasterXML/jackson-module-scala#211]
This test will fail at assertion

``` scala
case object TestObject

val mapper = new ObjectMapper() with ScalaObjectMapper
mapper.registerModule(DefaultScalaModule)

val original = TestObject
val deserialized = mapper.readValue[TestObject.type](mapper.writeValueAsString(original))

assert(deserialized == original)
```

After quick investigation i found out that original and deserialized are two instances of the case object. In my opinion it is a bug since I wound never expect to have two instances of a case object in one JVM.

**Comment by christophercurrie** [comment]
You are correct that the API you are using does not handle this correctly. That said, the underlying Jackson API being used expects to create a new object; it might be possible to work around this internally, but I think it would be more correct for the API to throw an exception in this case.

What you want to do in this case is to use an updating reader:

``` scala
val deserialized =
  mapper.readerForUpdating(TestObject).readValue(mapper.writeValueAsString(original))
```

This should allow your test to pass.

**Comment by ittaiz** [comment]
I have a similar issue but I'm trying to deserialize a complex object which has a case object in depth 3. AFAIU the API the `readerForUpdating` won't help me there and I didn't find something else in the API to help me. Any ideas?

**Comment by jqno** [comment]
We ran into the same issue. It turns out that `Constructor.newInstance` actually replaces the existing reference to the case object as well, which is quite insidious. See https://stackoverflow.com/q/55702041/127863 for some background.

We worked around this with this hack:

```scala
def deserialize[T](content: String, valueType: Class[T]): T
  getScalaSingletonInstance(valueType)
    .getOrElse(mapper.readValue(content, valueType))

private def getScalaSingletonInstance(c: Class[_ <: T]): Option[T] =
  c.getDeclaredFields.find(_.getName == "MODULE$").map(_.get(null).asInstanceOf[T])
```

(There is a cleaner way to check if something is a (case) object: https://stackoverflow.com/a/53456695/127863, but this solution was good enough for our purposes.)

It would be nice if Jackson supported this sort of thing out of the box though.

**Comment by pjfanning** [comment]
Thanks @jqno - I've added a ScalaObjectDeserializerModule for jackson-module-scala 2.13.0 (this change does not appear in 2.13.0-rc2) - this is based on your code snippet.

ScalaObjectDeserializerModule is not part of DefaultScalaModule. If no issues are reported in 2.13.x, I will add it to DefaultScalaModule for jackson-module-scala 2.14.0.

https://github.com/FasterXML/jackson-module-scala/commit/0f0c54b6620691f1cdb83451d5c5426ea96b2f87 has the change and test cases that demonstrate how to use ScalaObjectDeserializerModule

**Comment by pjfanning** [comment]
I'm going to make ScalaObjectDeserializerModule part of DefaultScalaModule in v2.16.0 release - see #601
