### ISSUE TITLE
Generate json schema

### ISSUE THREAD

**Issue by kfiron** [FasterXML/jackson-module-scala#216]
Hi,
I could not find a way to generate Json Schema from Scala case classes. 
I need it for Api Documentation using Swagger, any chance you support that?

**Comment by cowtowncoder** [comment]
This sounds more like a question to the jackson-user mailing list: https://groups.google.com/forum/#!forum/jackson-user

but the module for JSON Schema generation is

https://github.com/FasterXML/jackson-module-jsonSchema

and it should work for scala types similar to regular jdk classes and POJOs.

**Comment by kfiron** [comment]
Thanks
