### ISSUE TITLE
Project homepage refusing connection

### ISSUE THREAD

**Issue by OndrejSpanel** [FasterXML/jackson-module-scala#228]
When I try to access the project homepage at http://wiki.fasterxml.com/JacksonModuleScala, I get an error ERR_CONNECTION_REFUSED.

This page is listed as a project homepage in the Maven repository of the last available artifact at http://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-scala_2.11/2.6.1

**Comment by prb** [comment]
Fixed.
