### ISSUE TITLE
Strange error "Could not find creator property with name" with multiple constructors

### ISSUE THREAD

**Issue by OndrejSpanel** [FasterXML/jackson-module-scala#231]
When I run the code below with Jackson 2.6.3, I get an error during deserialization:

```scala
import com.fasterxml.jackson.annotation._
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper

object Main extends App {

  // uncommenting following line makes error disappear - understandable workaround
  //@JsonIgnoreProperties(Array("dummy"))
  class Assembly(val script: String, dummy: Int) {
    @JsonCreator
    def this(name: Int)(script: String) = {
      this(script, 0)
    }

    // uncommenting following line makes error disappear - strange
    //def this(script: String) = this(script, 0)
  }

  val jacksonMapper = new ObjectMapper() with ScalaObjectMapper

  jacksonMapper.registerModule(new DefaultScalaModule)

  val toSave = new Assembly(0)("script")

  val out = jacksonMapper.writeValueAsString(toSave)
  println(out)

  val check = jacksonMapper.readValue(out, classOf[Assembly])
  println(check)
}
```

> Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'dummy' (in class Main$Assembly)
 at [Source: {"script":"script"}; line: 1, column: 1]

It is possible to use `JsonIgnoreProperties` as a workaround.

It seems the Jackson is somehow confused the by the constructors and is listing `dummy` as a property. Adding another constructor makes the error go away.

**Comment by OndrejSpanel** [comment]
When I try to simplify the code even more, I get a bit different error. I am unable to decide how much is the error related - I will be glad to create a separate issue if needed.

The code is:

```scala
import com.fasterxml.jackson.annotation._
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper

object Main extends App {

  class Assembly(val script: String, dummy: Int) {
    @JsonCreator
    def this(script: String) = {
      this(script, 0)
    }

    // uncommenting following line makes error disappear - strange
    //def this() = this("", 0)
  }

  val jacksonMapper = new ObjectMapper() with ScalaObjectMapper

  jacksonMapper.registerModule(new DefaultScalaModule)

  val toSave = new Assembly("script")

  val out = jacksonMapper.writeValueAsString(toSave)
  println(out)

  val check = jacksonMapper.readValue(out, classOf[Assembly])
  println(check)
}
```

The error is:

> Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Conflicting property-based creators: already had explicitly marked [constructor for Main$Assembly, annotations: [null]], encountered [constructor for Main$Assembly, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}]

Again, uncommenting the line with the default constructor makes the error disappear.

**Comment by nbauernfeind** [comment]
A bug fix for this (hopefully works) is going to be released in v2.6.5, and v2.7.2 (note: 2.7.0/2.7.1 are not going to be released since they won't work). Can you please upgrade and check if #236 fixes your issue?

**Comment by OndrejSpanel** [comment]
The issue can still be seen with the repro above with both 2.6.5 and 2.7.2.

**Comment by nbauernfeind** [comment]
Sorry I should have run through this test, too; I just assumed it was related to another JsonCreator issue.

Very weird behavior! I'll track this down. FWIW, it looks like this works:
```scala
  class Assembly(val script: String, dummy: Int) {
    @JsonCreator
    def this(name: Int)(script: String) = {
      this(script, 0)
      println("Creator Run")
    }
    def foo(): Unit = {} // without this method it fails
  }
```

**Comment by OndrejSpanel** [comment]
We are hitting what we think is the same issue, however in a much more complex code, and no matter what `foo` functions are added into the `Assembly`, the deserialization ends with error:

`com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class Xxxxx] value failed (java.lang.IllegalArgumentException): argument type mismatch`

Is there something we can do to help fixing this?
