### ISSUE TITLE
Feature request: initialization of empty fields with their default value during deserialization

### ISSUE THREAD

**Issue by crumbpicker** [FasterXML/jackson-module-scala#239]
Do you think it could be possible to initialize fields with their default value if they are not defined in the JSON doc being deserialized ?

**Comment by christophercurrie** [comment]
This is another long-standing request. See #87.

**Comment by crumbpicker** [comment]
Ok thanks. Sorry for the duplicated entry. I searched for this issue but it seems I typed the wrong keywords ;-)

**Comment by pjfanning** [comment]
I think this was fixed with https://github.com/FasterXML/jackson-module-scala/issues/87
