### ISSUE TITLE
Possible problem with "NON_EMPTY" rule for primitive values

### ISSUE THREAD

**Issue by crumbpicker** [FasterXML/jackson-module-scala#244]
After switching to the Jackson Module 2.7.2 I have the same issue than this one:
https://github.com/FasterXML/jackson-databind/issues/849

The symptom is that primitive fields equals to zero are not exported in the JSON string when including NON_EMPTY fields.

The problem seems to be solved in Jackson core. Is there a compatibility issue with the module ?

**Comment by crumbpicker** [comment]
Sorry about this. This was a mistake in my POM.
I was erasing the appropriate version of the module by an older one.

**Comment by cowtowncoder** [comment]
@crumbpicker Right, this sounds very much like 2.6 behavior, and something that has caused lots of grief. Behavior in 2.7 same as 2.5 and before: default values like `0` for `int` may now be excluded by using `NON_DEFAULT`, and `NON_EMPTY` is strictly reserved for things with "more natural" concept of emptiness (Strings, arrays/Collections/Maps, referential types like Optional).
