### ISSUE TITLE
Verify Error with FasterXML

### ISSUE THREAD

**Issue by ruppalapati** [FasterXML/jackson-module-scala#250]
Running on JDK 1.8.0_77 and using Faster XML 2.7.2 jars

java.lang.VerifyError: class com.fasterxml.jackson.module.scala.ser.ScalaIteratorSerializer overrides final method withResolved.(Lcom/fasterxml/jackson/databind/BeanProperty;Lcom/fasterxml/jackson/databind/jsontype/TypeSerializer;Lcom/fasterxml/jackson/databind/JsonSerializer;)Lcom/fasterxml/jackson/databind/ser/std/AsArraySerializerBase;
	java.lang.ClassLoader.defineClass1(Native Method)
	java.lang.ClassLoader.defineClass(ClassLoader.java:763)

**Comment by cowtowncoder** [comment]
This is almost certainly a version discrepancy; most likely you have older `jackson-databind` in classpath. Minor versions across Jackson components need to match as a general rule: sometimes similar minor versions work together nicely, but not always.

**Comment by ruppalapati** [comment]
Yep that was it. There was a duplicate in the classpath that was causing this error. Thanks for taking the time to respond.
