### ISSUE TITLE
CachingParanamer breaks java.io.Serializable

### ISSUE THREAD

**Issue by cresny** [FasterXML/jackson-module-scala#266]
using v 2.7.2, trying to serialize an ObjectReader instance (used in a Flink serialized function), I get this error:

com.fasterxml.jackson.module.paranamer.shaded.CachingParanamer
java.io.NotSerializableException: com.fasterxml.jackson.module.paranamer.shaded.CachingParanamer
	
I have verified that the ObjectReader instance does serialize correctly id the DefaultScalaModule is not registered. Is there a workaround for this?

**Comment by cowtowncoder** [comment]
Probably won't make much difference, but the latest is 2.7.4, so might make sense to try it just to make sure.

As to problem itself, this would be `Paranamer` class, just shaded, which we can not do much about, at least directly. It would be necessary to know call/dependency graph. It looks like paranamer module uses `CachingParanamer`, so fix should probably go in there. I'll file a bug for the project, to see if it can be isolated and hopefully fixed.

**Comment by cresny** [comment]
Thanks, I caught this at the end of the day, too brain-dead to realize it's an easy workaround in scala using @transient lazy val.  So there's no urgency at least for me.

**Comment by cowtowncoder** [comment]
For what that is worth, it is fixed for paranamer module for next releases, since mapper/reader/writer ought to remain serializable.
