### ISSUE TITLE
Release 2.8.1

### ISSUE THREAD

**Issue by KalyanAkella** [FasterXML/jackson-module-scala#276]
Can you please release `2.8.1` ?

Our issue being, the latest version of this module available in the Maven repos is `2.8.0.rc2`. But that version does not have the fix for issue: https://github.com/FasterXML/jackson-modules-base/issues/13. This is causing our Spark jobs to fail.

Please help.

**Comment by ddrozdov** [comment]
Are there any plans for the release?

**Comment by omervk** [comment]
Thank you for the great work so far. :)
Would love to hear about plans to release a version compatible with the 2.8.x releases as more and more of my other dependencies are moving there and I am forced not to update.

**Comment by nbauernfeind** [comment]
2.8.1 and 2.8.2 have now been released.
