### ISSUE TITLE
Null pointer exception when trying to deserialize into Either[]

### ISSUE THREAD

**Issue by johno1985** [FasterXML/jackson-module-scala#287]
Hi,

I am trying to deserialize a json string into an object of type Either[MyError, MyResult]

I am using jackson=module-scala 2.7.4, scala v 2.11

I am using the following:

``` scala
case class MyInput(
                  val1: String,
                  val2: String
                )

case class MyResult(val1: Boolean,
                          val2: String,
                          val3: String,
                          val4: String,
                          val4: String,
                          val5: String)

case class MyError(status: Int)

case class MyType(input: MyInput, expectation: Either[MyError, MyResult])

val input = Input("Hello", "World")
val ra = MyResult(true, "ae", "nm", "am", "nc", "de")
val ira = MyType(input, Right(ra))

JacksonMapper.writeValueAsString(ira)
```

This produces the following json:

``` json
{
    "input":{
            "val1":"Hello",
            "val2":"World"
        },
    "expectation":{
        "r":{
                "val1":true,
                "val2":"ae",
                "val3":"nm",
                "val4":"am",
                "val5":"nc",
                "val6":"de"
            }
    }
}
```

When trying to deserialize using:

``` scala
JacksonMapper.readValue(req.body, classOf[MyType])
```

I receive the following null pointer exception:

``` bash
Caused by: java.lang.NullPointerException: null
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1017) ~[jackson-databind-2.7.4.jar:2.7.4]
    at com.fasterxml.jackson.module.scala.deser.EitherDeserializer.deserializeValue(EitherDeserializer.scala:43) ~[jackson-module-scala_2.11-2.7.4.jar:na]
    at com.fasterxml.jackson.module.scala.deser.EitherDeserializer.deserializeEither(EitherDeserializer.scala:55) ~[jackson-module-scala_2.11-2.7.4.jar:na]
    at com.fasterxml.jackson.module.scala.deser.EitherDeserializer.deserialize(EitherDeserializer.scala:67) ~[jackson-module-scala_2.11-2.7.4.jar:na]
    at com.fasterxml.jackson.module.scala.deser.EitherDeserializer.deserialize(EitherDeserializer.scala:12) ~[jackson-module-scala_2.11-2.7.4.jar:na]
```

Can you help?

**Comment by johno1985** [comment]
After playing around it looks like the deserialiser works fine for primitives but not for custom objects

**Comment by cowtowncoder** [comment]
@johno1985 there haven't been tons of changes, but it's always a good idea to ensure that the latest patch version of the minor version is used, both for `jackson-databind` and `jackson-module-scale`. 
So make sure to check with version `2.7.8`, just in case.

From stack trace it would seem like `EitherDeserializer` is passing wrong state (or not being initialized properly). But what is strange is that `deserializeWithType()` is being called without polymorphic types -- that seems wrong.

**Comment by cowtowncoder** [comment]
@nbauernfeind I don't know exactly what is wrong, but I have strong suspicion that `EitherDeserializer.scala` is messed up. It should not call `deserializeWithType()` without polymorphic handling being enabled, and `TypeDeserializer` being detected. But from code it seems to be calling it from regular `deserialize` too, which would be wrong even if it didn't bump into NPE...

**Comment by johno1985** [comment]
Thanks @cowtowncoder, I'll upgrade to the latest minor and see if that makes any difference

**Comment by johno1985** [comment]
Hi @cowtowncoder, I've upgraded to version 2.7.8 and that has had no effect
