### ISSUE TITLE
ScalaObjectMapper is correctly running on spark local, throw Exception on spark cluster

### ISSUE THREAD

**Issue by Presageee** [FasterXML/jackson-module-scala#288]
I'm running my sparkstreaming job on spark 1.6 and using Jackson-module-scala_2.10-2.8.3.It is correctly run on local model,but submit to cluster which is throw Exception:
`Exception in thread "main" java.lang.AbstractMethodError: SvwSensefaceCaptureStreaming$$anon$1.com$fasterxml$jackson$module$scala$experimental$ScalaObjectMapper$_setter_$com$fasterxml$jackson$module$scala$experimental$ScalaObjectMapper$$typeCache_$eq(Lorg/spark-project/guava/cache/LoadingCache;)V`

how can i do to solve it?
thanks

**Comment by alexandrnikitin** [comment]
I also encountered this issue using the `2.2.2` version and `2.8.3`.
I found a solution on SO http://stackoverflow.com/a/32495622/974487 and solved it by removing `ScalaObjectMapper` from the mapper creation:
```
       val rdd2 = rdd.mapPartitions(xs => {
-        val mapper = new ObjectMapper() with ScalaObjectMapper
+        val mapper = new ObjectMapper()
         mapper.registerModule(DefaultScalaModule)
...
```
I'm still not sure about the root of the issue.
