### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by axel22** [FasterXML/jackson-module-scala#295]
Would it be possible to release jackson Scala module for 2.12?

It looks like it's not available at Maven central at the moment:

http://central.maven.org/maven2/com/fasterxml/jackson/module/

Thanks!

**Comment by cowtowncoder** [comment]
Um, isn't there multiple ones available, like:

http://central.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12.0-RC1/

or is this specifically about ensuring module works with 2.12 Final release? (and if so, do existing ones not work?)

Plan is to make sure 2.8.5 is released with scala 2.12 I think; but 2.8.4 could also be done (scala module 2.8.4 wasn't released along with core components it seems).

**Comment by axel22** [comment]
Apparently, 2.12 final is not compatible with the RC1.

Having just 2.8.5 with Scala 2.12 would also be great.

**Comment by seratch** [comment]
@cowtowncoder

In the Scala world, RCs release for new major version (in this case, 2.12) is not binary compatible with the final version. The absence of the release version which has `_2.12` suffix enforces library users to have a hack in sbt configurations.

If there is no concern, please consider releasing for 2.12 final. I've sent [a pull request for this ticket](https://github.com/FasterXML/jackson-module-scala/pull/294
) yesterday. (It's ok to skip merging my PR but anyway, please release for 2.12)

**Comment by cowtowncoder** [comment]
@seratch Ok. I can't do Scala release myself, but either @christophercurrie or @nbauernfeind should be able to. Should be possible to release 2.8.4 with scala 2.12-final.

**Comment by seratch** [comment]
@cowtowncoder Thanks! Great to hear that.

If you all are busy for other projects and you're interested in increasing the maintainers of this project, let me know. I will be able to actively work on deployments and reviewing/merging minor fixes that don't bring breaking changes.

**Comment by axel22** [comment]
+1 thanks a lot!

**Comment by cowtowncoder** [comment]
@seratch I suspect Christopher and Nate would not mind help at all, but I'll let them comment when they get a chance.

**Comment by seratch** [comment]
Any updates on this? (I'm sorry for the rush, though)

**Comment by mbknor** [comment]
+1

**Comment by christophercurrie** [comment]
Version 2.8.4 is now built for 2.12.0 and is on its way to Maven central.

**Comment by seratch** [comment]
@christophercurrie Thank you so much 👍

**Comment by axel22** [comment]
@christophercurrie Thanks a lot!

**Comment by pjfanning** [comment]
Would it be possible to publish a 2.7.8 jar with scala 2.12 support?

**Comment by christophercurrie** [comment]
@pjfanning technically possible but will require some custom branch and release shenanigans. I've filed #297 to track the request.

**Comment by mbknor** [comment]
2.7.9 with Scala 2.12.1 is now released

**Comment by cowtowncoder** [comment]
@mbknor Most excellent, thank you!
