### ISSUE TITLE
2.8 is unable to handle Option of a case class

### ISSUE THREAD

**Issue by pshirshov** [FasterXML/jackson-module-scala#299]
I have the following model:

```
  case class WithAnything[T](content: T, id: String)
  class Something(meta: ObjectNode)
```

So, 2.7 is able to deserialize the following json into this model:

`{"content": {"meta" : {"key" : "value"}}, "id": "something"}`

when called like so:

`mapper.readValue[WithAnything[Option[Something]]](...)`

Jackson 2.8 fails to do that, it always returns just `Some(Map(meta -> Map(key -> value)))` as a value of `content` field.

**Comment by nbauernfeind** [comment]
Thanks for the report. Sorry for the delay. I've reproduced this issue and tracked it down.

**Comment by pshirshov** [comment]
During this time I've dropped Jackson (mostly because of this issue) in favor of Circe.
