### ISSUE TITLE
How to override deserialization of null to Option[_]?

### ISSUE THREAD

**Issue by kdubezerra** [FasterXML/jackson-module-scala#300]
How can I, using jackson, override the deserialization from json to `Option[Something]` when the value in json is `null` (not the string `"null"` though, but just `null`)?

For example, say I have `case class MyType(data: Option[MyType])`. For the following json

    {
      "data": null
    }

I get `MyType(None)`, but I'd like to get `MyType(Some(something_else))`, or at least be able to override jackson's behaviour when an `Option[_]` field is `null` in json.

I created a custom deserializer like `class MyTypeDeserializer extends JsonDeserializer[MyType]`, which works fine if `data` is a string `"null"`. However, if it's just `null` (as it must be due to my requirements), it simply doesn't work. I overrode both `getNullValue` and even `getEmptyValue` of my custom deserializer, which works for non-Option types, but still to no avail. Jackson simply doesn't call my deserializer if I'm deserializing to an `Option[MyType]` and the value is `null`...

**Comment by pjfanning** [comment]
Closing this as this seems to work in 2.13 branch - added test https://github.com/FasterXML/jackson-module-scala/commit/f362bd4def7911a6582c808a80be3251f25f0b1e

Reopen if you have a test scenario that is still not working.
