### ISSUE TITLE
Ensure consistency with Javaslang-Jackson serialization/deserialization.

### ISSUE THREAD

**Issue by Diagoras** [FasterXML/jackson-module-scala#303]
[It looks like the Javaslang-Jackson project uses "left" and "right"](https://github.com/javaslang/javaslang-jackson/blob/master/src/main/java/javaslang/jackson/datatype/serialize/EitherSerializer.java) when serializing an Either, while this project uses "l" and "r". For consistency, both projects should probably use the same format.

Should you change, or should they? Personally, I think the full "left" and "right" is clearer.

**Comment by cowtowncoder** [comment]
I can't comment much, other than suggesting that it might make sense to add support for allowing `l` and `r` as aliases on deserialization, for interoperability.
And that if default names were changed it'd need to be for 2.9 and not earlier; if so, aliases should definitely be allowed for deser.

**Comment by Diagoras** [comment]
Hmm, so the idea is that this project should support deserializing from "left" and "right", while Javaslang-Jackson should support deserializing "l" and "r"? While I'd prefer if there was an agreed upon standard for representing Either type in JSON, I get that preserving backwards compatibility makes that impossible. Let me open a ticket with that project and see if they agree with your reasoning.

Thanks!

**Comment by Diagoras** [comment]
[Opened a related issue on the Javaslang-Jackson project.](https://github.com/javaslang/javaslang-jackson/issues/98)
