### ISSUE TITLE
Release 2.8.5 of Scala module(s)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#304]
As per title, other components are out, and bom-2.8.5.1 as well which refers to 2.8.5 of all the components.

**Comment by asanderson** [comment]
What's the latest status of this? An estimate of when released?

**Comment by cowtowncoder** [comment]
This is up to maintainers who can build and deploy this module: currently I think this means @christophercurrie and @nbauernfeind. So whenever they have time to do the process.
My setup fails on deploy part for reasons I do not understand, related to `sbt` handling or setup (as best I can see).

There are no other reasons holding back the release as far as I know: that is, version of `2.8.5` to release is not pending for fixes (AFAIK).

**Comment by asanderson** [comment]
Well, considering we're now up to release 2.8.6 of jackson, is this module going to be supported any longer? @christophercurrie @nbauernfeind  Just need to know for planning purposes.

**Comment by cowtowncoder** [comment]
@asanderson I'll send a note to mailing list to see if we could expand pool of "release managers" (that is, someone with access & knowledge to push a release). And of course if you think you could help would be happy to deputize. :)

**Comment by jvwilge** [comment]
@asanderson I'd really like support for 2.8.5 since spring-boot 1.4.3 depends (and some other dependencies we use on our project) on this version. Of course it is possible to add 2.8.6 to spring-boot, but I rather stick with the dependencies the spring guys picked/tested for us.

**Comment by mbknor** [comment]
2.8.5 and 2.8.6 is now available in maven central

**Comment by asanderson** [comment]
Very cool! Many thanks!

**Comment by cowtowncoder** [comment]
@mbknor Thank you for doing these!
