### ISSUE TITLE
Release 2.6.x for Scala 2.12

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#306]
I've been testing some code that depends on Jackson 2.4 (eg swagger) and so far, I can only safely upgrade to Jackson 2.6 due to some in changes in Jackson-Databind in 2.7. I would like to at least start by making a partial upgrade to Jackson 2.6. Relates to https://github.com/FasterXML/jackson-module-scala/issues/297

**Comment by pjfanning** [comment]
Looks like https://github.com/FasterXML/jackson-module-scala/pull/301 has already been attempted

**Comment by pjfanning** [comment]
https://issues.apache.org/jira/browse/SPARK-8332 details that they have attempted to use different jackson versions but have chosen to stick with jackson 2.6 for now.
I understand that 2.6 is end of life but I would appreciate it if we could just publish a scala 2.12 compatible jar without making any other significant changes. The core java jackson modules would not need to be updated.

**Comment by cowtowncoder** [comment]
FWTW there is now `2.7.9` version of Scala module for Scala 2.12:

http://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-scala_2.12

just in case that'd help (I realize comments suggested only 2.6 works).

**Comment by mbknor** [comment]
I have just release version 2.6.7.1 of jackson-module-scala - with scala 2.12-support
