### ISSUE TITLE
Duplicate field in scala jackson toJson or null in fromJson with inheritance

### ISSUE THREAD

**Issue by ozmad** [FasterXML/jackson-module-scala#309]
I have problem of duplicate field for the following classes structure.

classs Foo1 and Foo2 extends trait Foo
case class Con(foo: Foo)
Relation is defined with Jackson annotations. When serializing con(foo1) a field in foo1 is duplication (the field from Foo)

I've tried to replace JsonTypeInfo.As.PROPERTY with JsonTypeInfo.As.EXISTING_PROPERTY. It prevent duplicateion but on deserialization the field was null. Also tried def instead of val in the trait Foo
[This is my question in StackOverflow](http://stackoverflow.com/questions/41322173/duplicate-field-in-scala-jackson-tojson-or-null-in-fromjson-with-inheritance)
This is a complete example:

```
package mypackage


import com.fasterxml.jackson.annotation.JsonSubTypes.Type
import com.fasterxml.jackson.annotation.{JsonSubTypes, JsonTypeInfo}
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "prop")
@JsonSubTypes(Array(
	new Type(value = classOf[Foo1], name = "foo1"),
	new Type(value = classOf[Foo2], name = "foo2")
))
sealed trait Foo {
	val prop: String
}

case class Foo1(name1: String, prop: String) extends Foo {
	def this() = this(null, null)
}

case class Foo2(name2: String, prop: String) extends Foo {
	def this() = this(null, null)
}

case class Con(foo: Foo)

object MyTast {

	val mapper = new ObjectMapper() with ScalaObjectMapper
	mapper.registerModule(DefaultScalaModule)

	def fromJson[T](json: String)(implicit m: Manifest[T]): T = {
		println(s"-fromJson menifest = $m")
		mapper.readValue[T](json)
	}

	def toJson(value: Any): String = {
		mapper.writeValueAsString(value)
	}

	def main(args: Array[String]): Unit = {
		val con = Con(Foo1("foo1", "foo1"))
		val con1JsonStr = toJson(con)
		if (con.foo.prop == null) throw new RuntimeException("1")
		println(con)
		println(con1JsonStr)
		if ("""{"foo":{"prop":"foo1","name1":"foo1","prop":"foo1"}}""" == con1JsonStr) throw new RuntimeException("duplicate prop")

		val con1FromJson = fromJson[Con](con1JsonStr)
		if (con1FromJson.foo.prop == null) throw new RuntimeException("prop was null")

		val con1FromCleanJson = fromJson[Con](con1JsonStr.replace(""","prop":"foo1"""", ""))
		if (con1FromCleanJson.foo.prop != null) throw new RuntimeException("after removing field I would expect it to be null")
	}
}
```

**Comment by pjfanning** [comment]
This still seems to be an issue - added test https://github.com/FasterXML/jackson-module-scala/commit/59504aa9e1793e6c1d0f44df6e55b432fe18b5b1

**Comment by pjfanning** [comment]
If the JsonTypeInfo annotation is omitted, serialization works fine.

**Comment by pjfanning** [comment]
I'm going to close this as invalid - the JsonTypeInfo property attribute should map to a field name that does not match one of the class fields - it is a separate field that provides a hint to jackson when it needs to deserialize the json - this is the fix I made to the test case - https://github.com/FasterXML/jackson-module-scala/commit/32cd0e57bf498cf9cc9938981357dd6f54f05fb2
