### ISSUE TITLE
Serialize Some(null)

### ISSUE THREAD

**Issue by provegard** [FasterXML/jackson-module-scala#314]
My application sends JSON to another application that is quite picky. In particular, it distinguishes between a property having value `null` and not being present.

I use `Option` for the property in question, and with value `None` the property is correctly omitted from the resulting JSON. However, when I try to serialize `Some(null)`, I get an NPE here:

https://github.com/FasterXML/jackson-module-scala/blob/fd3055b932e468ce784b4ffb090ccd899f221d57/src/main/scala/com/fasterxml/jackson/module/scala/ser/OptionSerializerModule.scala#L146

Is there any workaround?

**Comment by pijusn** [comment]
Work-around we use is to provide custom `OptionSerialiser` which does not have the issue.

**Comment by nbauernfeind** [comment]
This was fixed in 2.9.4. I've added a regression test to hope it doesn't happen again.

**Comment by provegard** [comment]
Great, thanks!

**Comment by mosesn** [comment]
I suspect that we need to change it so that NON_ABSENT doesn't set `suppressNulls` [to be true][0].

[0]: https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/ReferenceTypeSerializer.java#L200-L203

**Comment by provegard** [comment]
@mosesn Sorry about the late reply. It sort of fixed it, in the sense that the NPE is gone. However, I still need a custom serializer since the protocol distinguishes between a property with value `null` and an absent property. In other words, I need `Some(null)` to serialize to `null` for properties of a particular class.
