### ISSUE TITLE
Release 2.7.9 and 2.8.7 of Scala module (including 2.12 if feasible)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#315]
(note: obsoletes #297)

As part of 2.7.9, let's make sure Scala module gets released as well.

**Comment by cowtowncoder** [comment]
Ditto for 2.8.7.

**Comment by mbknor** [comment]
2.8.7 is now released

**Comment by mbknor** [comment]
2.7.9 with Scala 2.12.1 is now released
