### ISSUE TITLE
Release 2.9.0.pr2

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-module-scala#321]
Here are the [entries in the bom](https://github.com/FasterXML/jackson-bom/blob/jackson-bom-2.9.0.pr2/pom.xml#L269-L283)

**Comment by cowtowncoder** [comment]
Forgot to request this from Scala maintainers.

/cc @mbknor @nbauernfeind

**Comment by mbknor** [comment]
2.9.0.pr2 Is now released

**Comment by cowtowncoder** [comment]
Excellent, thank you again!
