### ISSUE TITLE
Deserialize json to trait or polymorphic case class

### ISSUE THREAD

**Issue by spandananitdgp** [FasterXML/jackson-module-scala#345]
I have a use case where I have to deserialize a field of case class into a case class, based on the value of another field.

case class Parent(`type`: String,
                                item: Item)
case class Item()
case class A(id: String, field1: String) extends Item
case class B (id: String, field2: String) extends Item.

When I deserialize a json:
{
   "type" : "A"
    "item" : {
          "id" : "A1"
           "field1" : "something"
     }
}

my deserializer should pick case class for "item" based on the value of "type". How can I achieve this??

My attempt at this is : 
object ItemDeserializer extends JsonDeserializer[Item] {
  override def deserialize(p: JsonParser, ctxt: DeserializationContext): Item = {
    var parent = p.readValueAs(Parent.getClass)
    if (parent.asInstanceOf[Parent].`type` == "A") {
      new A() //This is where I am confused what to do
    } else {
      new B() /This is where I am confused what to do
    }
  }
}

and ObjectMapper is as follows:
val mapper = new ObjectMapper() with ScalaObjectMapper
  val module = new SimpleModule()
  module.addDeserializer(Item.getClass, ItemDeserializer)
  mapper.registerModule(DefaultScalaModule)

**Comment by cowtowncoder** [comment]
Have you tried the standard way, use of `@JsonTypeInfo`? That is designed to implement what you are trying to do here I think.

**Comment by spandananitdgp** [comment]
I tried JsonTypeInfo. 
```
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, property="type")
@JsonSubTypes(Array(
  new Type(value=classOf[A], name="A"),
  new Type(value=classOf[B], name="B")
))
abstract class Item()
```

This will deserialize a json into Item based on a field called "type". Something like this:

```
{
 "type": "A",
  "id" : "A1"
 "field1": "something
}
```
 
But I want to deserialize Parent's item based on "type" mentioned in Parent.

```
{
"type": "A",
"item" : {
 "id" :"A1",
"field1": "something"
}
}

```

**Comment by cowtowncoder** [comment]
Try with `include = EXTERNAL_PROPERTY`, on field that refers to value (in parent class). This is different from default `PROPERTY` which assumes inclusion within Object.

**Comment by spandananitdgp** [comment]
Thanks! That worked.
