### ISSUE TITLE
maven artifacts for 2.9.2 missing

### ISSUE THREAD

**Issue by tedyu** [FasterXML/jackson-module-scala#350]
There is no 2.9.2 under https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-scala_2.10

No artifact for jackson-module-scala_2.11 either

When would the artifact be populated ?

Thanks

**Comment by tedyu** [comment]
@mbknor @nbauernfeind 
Can you let me know when the artifacts can be populated ?

HBase is blocked on this.

Thanks

**Comment by mbknor** [comment]
Done. jackson-module-scala-2.9.2 is on its way to maven central

**Comment by tedyu** [comment]
5 hours passed.

I don't see 2.9.2 artifact at https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-scala_2.10

**Comment by mbknor** [comment]
sry.. my fault. I forgot to manually do the "release" in oss.sonatype.org.
I've fixed it now. The artifact should be available soon.

**Comment by mbknor** [comment]
Now it should be available (http://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.10/2.9.2/)

**Comment by cowtowncoder** [comment]
Thank you again!
