### ISSUE TITLE
Invalid request results in SocketException or NoHttpResponseException

### ISSUE THREAD

**Issue by tedyu** [FasterXML/jackson-module-scala#352]
Please see test:
https://github.com/apache/hbase/blob/master/hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestNamespacesInstanceResource.java#L272

Instead of getting code 400, we got NoHttpResponseException (with jackson 2.9) :

https://builds.apache.org/job/HBASE-Flaky-Tests/23340/testReport/junit/org.apache.hadoop.hbase.rest/TestNamespacesInstanceResource/testInvalidNamespacePostsAndPuts/
```
org.apache.http.NoHttpResponseException: localhost:46004 failed to respond
	at org.apache.hadoop.hbase.rest.TestNamespacesInstanceResource.testInvalidNamespacePostsAndPuts(TestNamespacesInstanceResource.java:271)
```
Is this expected ?

**Comment by cowtowncoder** [comment]
Wrong repository?
