### ISSUE TITLE
Jackson `2.8.11` release for Scala module

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#359]
I hope this should be easier than 2.9. So, 2.8.11 is out:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.11

and it'd be good to get Scala module out too. This is planned to be the last full 2.8.x release, closing the branch. So should perhaps simplify things a bit (I forget if there's any scala version deprecation involved here, perhaps not).

**Comment by mbknor** [comment]
hmm.. This one also fails with the same error as #357

Is it something wrong with my machine?

....

We need to figure this out..

**Comment by cowtowncoder** [comment]
Hmmh. It could be one of backported fixes. While nothing looks particularly suspicious, it could be either one of:

* https://github.com/FasterXML/jackson-databind/issues/1604
* https://github.com/FasterXML/jackson-databind/issues/1807

One thing you could try locally is to build against `2.8.10` and see if that'd work.
I would guess it does, which wouldn't help a lot. If it is easy enough to build against 2.8.11-SNAPSHOT could also try checking out various points in `2.8` to rule out PRs.
But I guess fundamentally, assuming it is side-effect of one of the fixes, something would probably have to change in the test. Or, in worst case, scala module... (worst just because it's not very easy to see how things work, sometimes).

**Comment by mbknor** [comment]
I have not tracked the issue down yet, but this is what I've found out so far:

I've been using the 2.8-branch for testing - I guess there are less changes between 2.8.10 and 2.8.11.

The problem is this line:
https://github.com/FasterXML/jackson-module-scala/blob/fd3055b932e468ce784b4ffb090ccd899f221d57/src/main/scala/com/fasterxml/jackson/module/scala/deser/UntypedObjectDeserializerModule.scala#L29

In 2.8.10, _mapDeser ends up with SortedMapDeserializer
In 2.8.11, it ends up with SeqDeserializer.

I have not figured out why yet, but I write it here for info/starting point

**Comment by cowtowncoder** [comment]
Ok. I don't know if change is problematic (it may well be), but for context that "untyped" deserializer is for use with `java.lang.Object` as nominal type (most often due to raw types / missing generic declaration). And override is needed, I think, to change mapping from JSON Object into Scala Map, not JDK Map (and perhaps ditto for Java List to Scala List).

**Comment by mbknor** [comment]
I found it the change causing the problem:

https://github.com/FasterXML/jackson-databind/commit/467589680add00ab49108bbbe7db375d81a75837#diff-71da9745111f01bc93519d574c2f9fabL416

```scala
if (baseType.isInterface()) {
    // The scala-test was relying on this line.
    newType = baseType.refine(subclass, tb, null, new JavaType[] { baseType });
} else {
    newType = baseType.refine(subclass, tb, baseType, NO_TYPES);
}
```

For 2.8.10, we end up with isMapLike == true, but for 2.8.11 we end up with isCollectionLike == true which breaks down the line..

I'm not sure if I have found a regression or not.. What do you think?

**Comment by cowtowncoder** [comment]
Hmmh. This could also be related to the fact that Scala module is not necessarily supporting type refinement (to support collection- / map-like) in the right place: things have changed a little.
So another place to look might be `TypeModifier`, to ensure it recognizes the need.

New code in this specific place is, I think, (more) correct. But I don't quite understand negative ramifications on Scala side.

Getting `CollectionLikeType` and `MapLikeType` right is important, since code in other areas relies on that.

**Comment by mbknor** [comment]
2.8.11 released
