### ISSUE TITLE
Serialization of Option: InvalidDefinitionException: Cannot construct instance of `scala.runtime.Nothing$

### ISSUE THREAD

**Issue by xmariachi** [FasterXML/jackson-module-scala#365]
Cannot serialize simple case classes with Options. 
I am trying to serialize this Session case class:

    @JsonCreator
    case class Session ( 
                    @BeanProperty @JsonProperty("events") events: Option[Set[Event]],
                    @BeanProperty @JsonProperty("merchantSiteId") merchantSiteId: Option[String] )
    } 

In my test I create a Session, with an empty Event set (it's the same if I have elements). For completeness, Event class is like this: 

    @JsonCreator
    case class Event( 
          @BeanProperty something : Option[String],
          // ...and some other properties like this
    }

Then I have a serializer and a deserializer classes. Will show creation of ObjectMapper only for brevity, it's the same in both: 

    val objectMapper = new ObjectMapper() with ScalaObjectMapper
    def configure() = {
      objectMapper.registerModule(DefaultScalaModule)
      objectMapper.configure(SerializationFeature.INDENT_OUTPUT, false)
      objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
      objectMapper.setSerializationInclusion(Include.NON_NULL)
      objectMapper.setSerializationInclusion(Include.NON_ABSENT)
    }

And definition of serializer and deserializer methods. This overrides a method for Kafka Streams serde, hence the topic:String field, but it is not used here anyway. I add it for completeness. 
Serializer function: 

    def serialize(topic: String, data: T): Array[Byte] = {
       return objectMapper.writeValueAsBytes(data)
    }

And deserializer. 

    def deserialize(topic: String, data: Array[Byte]): T = {
        fromJson(new String(data, 0, data.length, utf8))
    }    
    def fromJson[T](json: String)(implicit m: Manifest[T]): T = {
        objectMapper.readValue[T](json)
    }

So, in my test I do: 

    final val uid = Some("123456789")
    final val createdAt = Some("2345678")
    final val merchantSiteId = Some("1")
    final val pageviewEventType = Some("pageview")
    final val url = Some("http://test.com/test")
    // Below, I tested to pass None, Set or an actual Event Set to no avail, same problem.
    final val session = new Session(None, merchantSiteId, createdAt, uid, createdAt)
    val sessionSerializer = new JacksonSerializer[Session]
    sessionSerializer.configure()
    val sessionDeserializer = new JacksonDeserializer[Session]
    sessionDeserializer.configure()
    test("Testing Valid Session Serde") {
        val serializedSession = sessionSerializer.serialize("test-topic", session)
        val deserSession : Session = sessionDeserializer.deserialize("test-topic", serializedSession)
    }

It breaks with: 

     com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `scala.runtime.Nothing$` (no Creators, like default construct, exist): abstract type (need to add/enable type information?)
    [info]  at [Source: (String)"{"merchantSiteId":"1","createdAt":"2345678","visitorId":"123456789","endsAt":"2345678"}"; line: 1, column: 2]
    [info]   at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
    [info]   at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
    [info]   at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
    [info]   at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:72)
    [info]   at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
    [info]   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
    [info]   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
    [info]   at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:190)
    [info]   at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:189)
    [info]   at mypackage.JacksonDeserializer$$anon$1.readValue(JacksonDeserializer.scala:19)

It seems to not know the type to use, but I think it should be clear by the methods. Is there something I am missing here? Is it something not supported?
I have checked many issues out there, and have tried specifying the annotations you can see there, but it doesn't work with them or other ones. 

Built with:  

    scalaVersion := "2.12.3"

and: 

    "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.9.2",
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.2",

**Comment by brharrington** [comment]
You are not passing the type information through to `fromJson` so it is trying to decode it to `Nothing`. For example:

```scala
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.scalatest.FunSuite

class Issue365 extends FunSuite {

  private val mapper = new ObjectMapper()
  mapper.registerModule(DefaultScalaModule)

  def fromJson[T: Manifest](json: Array[Byte]): T = {
    val cls = manifest.runtimeClass.asInstanceOf[Class[T]]
    mapper.readValue[T](mapper.writeValueAsBytes(json), cls)
  }

  test("fails") {
    val input = Session(None)
    val decoded = fromJson(mapper.writeValueAsBytes(input))
    assert(input === decoded)
  }

  test("succeeds") {
    val input = Session(None)
    val decoded = fromJson[Session](mapper.writeValueAsBytes(input))
    assert(input === decoded)
  }
}

case class Session(events: Option[Set[Event]])
case class Event(something: Option[String])
```

**Comment by smparkes** [comment]
Stumbled across this because I had the same mistake. Suggest we can close this as it's an error on the part of the caller.
