### ISSUE TITLE
CsvMapper does not serialize / de-serialize Scala Option correctly

### ISSUE THREAD

**Issue by mlvn23** [FasterXML/jackson-module-scala#368]
I'm using version 2.9.4 for everything, but I also tried it with 2.7.x. The following code works with the ObjectMapper but not with the CsvMapper: 

```
        case class Record(key: String, value: Option[Double])

        val mapper = new CsvMapper with ScalaObjectMapper
        mapper.registerModule(DefaultScalaModule)

        val cls = classOf[Record]
        val schema = mapper.schemaFor(cls).withHeader
        val writer = mapper.writer(schema)
        val reader = mapper.readerFor(cls).`with`(schema)

        val goodCsv = writer.writeValueAsString(Record("good", Some(10.0)))
        val badCsv = writer.writeValueAsString(Record("bad", None))

        println(goodCsv)
        // key,value
        // good,10.0

        println(badCsv)
        // key,value
        // bad,

        println(reader.readValue[Record](goodCsv)) // Record(good,Some(10.0))
        println(reader.readValue[Record](badCsv))  // Record(bad,Some())  -> it deserialized into Option[String]

        // fails: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
        val d: Double = reader.readValue[Record](badCsv).value.get 

```

I also tried it with AtomicReference with the same result. Using Java and AtomicReference works as expected. See FasterXML/jackson-dataformats-text#76.

**Comment by pjfanning** [comment]
I modified the test above to use Option[BigDecimal] and it behaved better. I have seen general issues in another scenario with Jackson Scala Module and Option[T] where T is a type like Double, Int or Boolean - where it appears that Jackson treats the T as java.lang.Object - but when the T is not one of the primitive-like types (eg BigDecimal) that Jackson Scala Module does work out the T correctly.

**Comment by nbauernfeind** [comment]
This is, unfortunately, known and related to #243. I'm going to close as a duplicate.
