### ISSUE TITLE
publish 2.9.6 to maven

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#377]
Would it be possible to publish version 2.9.6?
The preparatory work appears to have been done but the jar isn't in maven yet.
https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-scala

**Comment by cowtowncoder** [comment]
Hmmh. As per #374, that should be the case already...

**Comment by mbknor** [comment]
My fault. It was stuck in stage at oss.sonatype.org.

I have now fixed it.

Den man. 18. jun. 2018, 06:37 skrev Tatu Saloranta <notifications@github.com
