### ISSUE TITLE
Jackson doesn't check type inside Option[Any] for primitive values

### ISSUE THREAD

**Issue by larsga** [FasterXML/jackson-module-scala#384]
That is, if I declare a field as `Option[Int]` I can easily load a String into it, which rather takes away the point of using a strictly typed structure in the first place.

Put Jackson etc on classpath, then start Scala interpreter and do this:

```
import com.fasterxml.jackson.databind.ObjectMapper
val mapper = new ObjectMapper()

import com.fasterxml.jackson.module.scala.DefaultScalaModule
mapper.registerModule(DefaultScalaModule)

import com.fasterxml.jackson.core.`type`.TypeReference

case class Test(number: Option[Int])

val t = new TypeReference[Test]{}

val v = mapper.readValue(""" {"number" : "WTF"} """, t).asInstanceOf[Test]
v: Test = Test(Some(WTF))
```

Now if you try to actually access the value:

```
scala> v.number
res2: Option[Int] = Some(WTF)

scala> v.number.get
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
  ... 29 elided
```

What's interesting is that for Option[CaseClass] Jackson _does_ detect it if I try to slip at string or something else in there. So it seems like this should be possible to solve, but having looked quickly at the source code I didn't spot any obvious way to do it.

**Comment by larsga** [comment]
Okay. IMHO this is a quite serious problem that takes away some of the point of the object mapping. Looking forward to having it solved.

**Comment by plokhotnyuk** [comment]
@larsga try jsoniter-scala https://github.com/plokhotnyuk/jsoniter-scala

It enforces strict type checking during parsing and binding for any value.

Also it is much safe and more efficient, see:
https://github.com/hseeberger/akka-http-json/pull/205#issuecomment-392472719
http://jmh.morethan.io/?source=https://plokhotnyuk.github.io/jsoniter-scala/oraclejdk8.json

**Comment by cowtowncoder** [comment]
@plokhotnyuk I would prefer you not advertising other libraries here. I understand you want to have users but please do advertising somewhere else
