### ISSUE TITLE
How to convert a missing list field into Nil?

### ISSUE THREAD

**Issue by grant-guo** [FasterXML/jackson-module-scala#386]
I have the following demo codes:

```
case class Person(
  @JsonProperty("first") first:String,
  @JsonProperty("last") last:String,
  @JsonProperty("phones") phones: Seq[String],
  @JsonProperty("address") address:Option[String],
  @JsonProperty("cars") cars: Seq[String]
)

  val mapper = new ObjectMapper()
  mapper.registerModule(DefaultScalaModule)

  val json =
    """
      {
        "first":"grant",
        "last":"guo",
        "phones":["416", "647"],
        "address":"abc"
      }
    """.stripMargin

  val person = mapper.readValue[Person](json, classOf[Person])
```

In the parsed `person` instance, `cars` field is a Java `null`, is there any way to convert it into `Nil` directly?

**Comment by nbauernfeind** [comment]
I'm not sure if there's a solution built-in to jackson that would treat a missing entry as an empty list. Technically a null object, empty list, and non-empty list are different scenarios one might want to detect based on the inputted json.

Work arounds you can try (I'm not sure if all will work):
- rename `cars` to `_cars` for the variable and add a getter that converts null's to empty Seq's
- use a JsonCreator that does this once at construction time
- convert the `Seq[String]` to an `Option[Seq[String]]` so you know it is optionally provided.

**Comment by Phil4** [comment]
I have the exact same issue. 
It seems strange to want to handle null values in Scala immutable collections.
Anyway, as workaround I used a var instead of a val:
`case class Person(
  ...
  @JsonProperty("phones") var phones: Seq[String],
  ...
) {
  phones = if(phones == null) Nil else phones
}`

**Comment by pjfanning** [comment]
merging with https://github.com/FasterXML/jackson-module-scala/issues/462
