### ISSUE TITLE
Support Scala 2.13.0-M5

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#391]
Would it be possible to publish a jar that's built with the latest scala 2.13 milestone?

Relates to https://github.com/FasterXML/jackson-module-scala/issues/379

**Comment by nbauernfeind** [comment]
Yes. I'll take care of this tomorrow. I made a comment on your PR. I'd
really appreciate the help if you have the time, otherwise I'll take care
of that too.

**Comment by pjfanning** [comment]
@nbauernfeind @mbknor would it be possible to publish jackson-module-scala 2.9.7 or 2.9.8 for scala 2.13.0-M5?

**Comment by mbknor** [comment]
It already exists:

https://search.maven.org/artifact/com.fasterxml.jackson.module/jackson-module-scala_2.13.0-M5/2.9.8/bundle

Den tor. 20. des. 2018, 15:43 skrev PJ Fanning <notifications@github.com:
