### ISSUE TITLE
Travis-CI jobs are failing because of JDK 10

### ISSUE THREAD

**Issue by SethTisue** [FasterXML/jackson-module-scala#396]
see https://github.com/FasterXML/jackson-module-scala/pull/395

where at e.g. https://travis-ci.org/FasterXML/jackson-module-scala/jobs/487686376

we see

```
oraclejdk10 is deprecated. See https://www.oracle.com/technetwork/java/javase/eol-135779.html for more details. Consider using openjdk10 instead.
```

**Comment by nbauernfeind** [comment]
Looks like @sullis fixed this on 2/12 in 99df77d2961b95b12454d3eae9f87dd2dadfdc64.
