### ISSUE TITLE
Deserialization of inner Enumeration class fails

### ISSUE THREAD

**Issue by xylo** [FasterXML/jackson-module-scala#401]
The (de)serialization of top level Enumeration classes works well.  But if you put the Enumeration class inside another object the deserialization fails with a ClassNotFoundException.

Example code:
```
object JsonTest extends App {

	object Kind extends Enumeration {
		type Kind = Value
		val text = Value
	}

	val jsonCode = JsonUtils.toJson(Kind.text)
	println(jsonCode)
	println(JsonUtils.fromJson[Kind.Value](jsonCode))

}
```

**Comment by sumannewton** [comment]
@xylo I am facing this issue continuously in one JVM. But in another JVM, I have the same code and same functionality but there it seems to deserialize the enum data properly. Can you confirm if this issue happens intermittently or non-intermittently? Can it work in any other case like in my latter JVM?

Enum looks like below:
```
object DataTypeInstances extends Enumeration {
  val Unknown: Value = Value(0)
  val Fractional: Value = Value(1)
  val Integral: Value = Value(2)
  val Boolean: Value = Value(3)
  val String: Value = Value(4)
}
```
And is placed in a file name DataType.scala. The same can be referred to [here](https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/DataType.scala).

Need your expertise in helping me understand how it is working in the first case and not in the second case continuously.
