### ISSUE TITLE
Deserialization issue with Option[IndexedSeq[UUID]]

### ISSUE THREAD

**Issue by allenjhan** [FasterXML/jackson-module-scala#408]
Hello,

I am aware of the issue with Option of primitive types being cast to strings. I have read the FAQ and used the solution provided. It works.

https://github.com/FasterXML/jackson-module-scala/wiki/FAQ

However, I am having another issue with the JSON parser. If a case class contains a member that is Option[IndexedSeq[UUID]], deserializing from a JSON should include a check for whether the UUID is a valid UUID. If not, normally an exception is thrown.

However, when I use the JSON parser, it currently permits an invalid UUID, such as "ffffffff-ffff-ffff-ffff-ffffffffffff" to be created in the IndexedSeq of the field.

Using annotations does not seem to solve the issue, or else I am going about it the wrong way. I have tried placing @JsonDeserialize(contentAs = classOf[IndexedSeq[java.util.UUID]]) in the problematic field in question, and this does not prevent an invalid UUID from being created.

**Comment by allenjhan** [comment]
I just checked if the JsonDeserialize annotation trick works for Option[UUID], and it appears not to. If an invalid UUID in a JSON is deserialized, it is natural to expect an exception to be thrown when thefromString method is used to create the UUID. Clearly that is not happening.

Is there some kind of workaround that will cause an exception to be thrown if an invalid UUID is passed in a field that either expects Option[UUID] or Option[IndexedSeq[UUID]]?

**Comment by allenjhan** [comment]
I just tested the deserializer on a case class with a simple UUID field. No exception is thrown if an invalid UUID is provided.

This is probably too much to hope for, but is there a way to force the deserializer to throw an exception if the UUID is invalid?

**Comment by plokhotnyuk** [comment]
@allenjhan w/a is to create a custom deserializer which will use the [fast-uuid](https://github.com/jchambers/fast-uuid/blob/master/src/main/java/com/eatthepath/uuid/FastUUID.java) library or just use the [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L2173) parser which will deserialize JSON array of UUID strings with full validation at speed up to 2Gb per second.

**Comment by allenjhan** [comment]
Apparently, the UUID I thought was invalid is not actually invalid. Jackson has built-in handling for UUID that  is not at fault here. Therefore, I am closing this bug report.

**Comment by plokhotnyuk** [comment]
@allenjhan "AfricaAmericaAustralia==" value is parsed successfully as valid UUID too.
