### ISSUE TITLE
SortedSet field deserialization

### ISSUE THREAD

**Issue by primislas** [FasterXML/jackson-module-scala#410]
Hey guys. I fail to deserialize classes with SortedSet fields.
I've tried jackson-module-scala versions 2.8.8 and 2.9.8 against scala 2.12.6.

Here's the simplest test:
```
import scala.collection.immutable.SortedSet
case class WithSortedSet(ss: SortedSet[Int] = SortedSet.empty)
```
```
      val mapper = new ObjectMapper() with ScalaObjectMapper
      mapper.registerModule(DefaultScalaModule)
      val fromArray = mapper.readValue[SortedSet[Int]]("[3,1,2]")

      val json = """{"ss":[5,3,4]}"""
      val toCaseClass = mapper.readValue[WithSortedSet](json)
```
Deserialization from array works just fine and produces a TreeSet. However, deserializing into a field fails with the following exception:
```
com.fasterxml.jackson.databind.JsonMappingException: Unsupported value type: java.lang.Object (through reference chain: com.lomicron.utils.json.WithSortedSet["ss"])
com.fasterxml.jackson.databind.JsonMappingException: Unsupported value type: java.lang.Object (through reference chain: com.lomicron.utils.json.WithSortedSet["ss"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
...
```

Which is actually thrown inside SortedSetDeserializerModule.
All of this is also true for TreeSet.

Am I missing something or is it indeed a bug?

**Comment by nbauernfeind** [comment]
I think you might be hitting this common issue:
https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-and-other-primitive-challenges

Have you tried using `@JsonDeserialize(contentAs = classOf[java.lang.Integer])` on the field?

**Comment by primislas** [comment]
Ah, contentAs does work. It didn't occur to me to blame primitives as other Int collections behave as expected, so I was searching for SortedSet questions and came back empty-handed. :)

This will do, thanks a lot!
