### ISSUE TITLE
release for scala 2.13.0-RC3

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#414]
2.13.0-RC2 could possibly be useful too

**Comment by dejan2609** [comment]
@mbknor can you please release **2.9.9** for Scala **2.13.0-RC2** ?

Related issue: **_Publish version 2.9.9_** #412

**Comment by pjfanning** [comment]
Release looks good. Thanks.

**Comment by dejan2609** [comment]
@mbknor please publish **2.9.9** for Scala **2.13.0**  

https://repo.maven.apache.org/maven2/com/fasterxml/jackson/module

Related PR: https://github.com/FasterXML/jackson-module-scala/pull/417
