### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by tdiethe** [FasterXML/jackson-module-scala#415]
When I try to deserialize a json string I'm getting an error. Minimal example:

```Scala
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule

val s = "{\"a\": 1}"
val mapper = new ObjectMapper()
mapper.registerModule(DefaultScalaModule)
val writer = mapper.writerWithDefaultPrettyPrinter
val json = writer.writeValueAsString(s)
```

for which I receive the following output:

```Scala
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonMappingException.<init>(Ljava/io/Closeable;Ljava/lang/String;)V
  com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:61)
  com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
  com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:718)
  ammonite.$sess.cmd45$Helper.<init>(cmd45.sc:6)
  ammonite.$sess.cmd45$.<init>(cmd45.sc:7)
  ammonite.$sess.cmd45$.<clinit>(cmd45.sc:-1)
```

Scala 2.11.12
Java 1.8
jackson-annotations = 2.9.0
jackson-core = 2.9.7
jackson-databind = 2.9.7
jackson-module-scala_2.11 = 2.9.7

No duplicates in the dependency tree for databind:

```Bash
mvn dependency:tree | grep jackson-databind
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.7:compile
```

**Comment by nbauernfeind** [comment]
Can you create a minimal github project and include reproduction steps? I'm guessing somehow the databind jar is not on your classpath at runtime. The NoSuchMethodError is caused because it cannot find a class in the databind jar at the time that is is complaining that the version of databind that it finds (if any) is incompatible with this version of the scala module.

**Comment by mbknor** [comment]
@tdiethe I think your code is wrong. You say you are deserializing json, but the code tries to serialize a String to json.

**Comment by cowtowncoder** [comment]
The original exception, at any rate, is due to incompatible versions of Jackson components: version of `jackson-databind` likely being much older than Scala module.

Will close, would need reproduction to reopen.
