### ISSUE TITLE
Remove Paranamer usage where possible

### ISSUE THREAD

**Issue by zhao-zihao** [FasterXML/jackson-module-scala#449]
I have a project based on scala 2.13, JDK 8, and jackson-module-scala 2.11.0. Recently we upgrade to JDK 11.

Then `jackson-module-scala` throw an `IndexOutOfBoundsException` from `BytecodeReadingParanamer` class.  
I noticed that the `BeanIntrospector.scala` of the `jackson-module-scala` import the problematic `com.thoughtworks.paranamer.BytecodeReadingParanamer`, which hasn't get updated since 4 years ago and it only support JDK 8.

**Comment by pjfanning** [comment]
jackson-module-scala unit tests run ok on OpenJDK 11 - if you provide a reproducible test case, we can look at it

**Comment by zhao-zihao** [comment]
@pjfanning Thanks for your help! I solved the issue!

We have a class like this:
```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ExampleProperty {
    @JsonProperty("name") private String name = null;
    @JsonProperty("value") private String value = null;

    @JsonCreator
    public ExampleProperty(String name, String value) {
        this.name = name;
        this.value = value;
        validate();
    }
```
The above code worked in JDK 8 but failed in JDK 11.  

To make it work, I removed  the `ScalaAnnotationIntrospectorModule` of  `DefaultScalaModule`, which uses the `paranamer` library(supports JDK 8) to get parameter names using Java reflection. And add `@JsonProperty` annotation to arguments. And the code would be like this:
```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ExampleProperty {
    @JsonProperty("name") private String name = null;
    @JsonProperty("value") private String value = null;

    @JsonCreator
    public ExampleProperty(@JsonProperty("name") String name, @JsonProperty("value") String value) {
        this.name = name;
        this.value = value;
        validate();
    }
```

**Comment by pjfanning** [comment]
@zhao-zihao that code you provided is plain java and not scala - do you use scala at all and if not, can you just remove the jackson-module-scala dependency?

**Comment by pjfanning** [comment]
@cowtowncoder it's easy to drop paranamer usage in jackson-module-scala if we replace it with Java8 specific code. With Jackson 3, is it the intention to drop support for Java 7 and below?

**Comment by cowtowncoder** [comment]
@pjfanning Yes, Jackson 3.0 is Java8+ only at this point and earlier versions will not be supported. There may even be question of requiring some later JDK version, but JDK8 for sure.

In addition, every module can decided if they might want to go Java 8 with 2.x as well: some modules do that (`jackson-module-kotlin` requires Java 8, and I think some datatype modules might as well). So it might make sense to consider going Java 8 with Scala module 2.12, for example?

**Comment by pjfanning** [comment]
Thanks @cowtowncoder, I would favour dropping Java 7 support in jackson-module-scala 2.12.0.

I might even try to remove the dependency on jackson-module-paranamer in jackson-module-scala 2.12.0.

**Comment by zhao-zihao** [comment]
> @zhao-zihao that code you provided is plain java and not scala - do you use scala at all and if not, can you just remove the jackson-module-scala dependency?

Yes. I am using the scala Play Framework 2.8.2.  
The app will give me an error like the following if I remove the `jackson-module-scala` completely. 
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of java.util.HashSetcom.microstrategy.modelservice.request.enums.ShowExpressionAsType out of START_OBJECT token
```

Then I add back the `IterableModule` to deserialize a HashSet parameter in HTTP Request. 
ExampleIterableModule.scala:
```
import com.fasterxml.jackson.module.scala.{ IterableModule}
class ExampleIterableModule extends IterableModule {}
```
JsonAPISerizlizer.java:
```
new ObjectMapper().registerModule(new ExampleIterableModule())
```

**Comment by pjfanning** [comment]
So, in jackson-module-scala 2.12.0-SNAPSHOT, I have dropped java 7 support (which only affects scala 2.10/2.11 as scala 2.12/2.13 already only supported java 8). I have removed the dependency on jackson-module-paranamer.

scala 2.10/2.11 builds still need paranamer as these scala versions build java classes without full java8 support.

**Comment by cowtowncoder** [comment]
Note: Scala 2.10 support was dropped from Jackson 2.12 so Paranamer dependency only exists for Scala 2.11.

**Comment by pjfanning** [comment]
@afsilvasantos where is jackson-module-scala in your stacktrace? You seem to be using play-json and play-json does not use jackson-module-scala - it only used plain jackson-databind.

Please do not raise this as a jackson-databind issue either - the Jackson team have limited time and will not want to debug Play for you. A Jackson only test case is what is needed if you expect anyone from Jackson team to debug your issue for you.

**Comment by khalilantique59** [comment]
@pjfanning https://stackdev.space/questions/delete-the-element-from-the-json-data

**Comment by pjfanning** [comment]
@khalilantique59 what is this link about? Are you being paid to spam OSS volunteers. There is a lot of chatter in the OSS community at the moment about bad actors paying people to waste the time of volunteers.
