### ISSUE TITLE
invesigate issue with defaulted params in case classes when value in json is null

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#453]
https://github.com/FasterXML/jackson-module-scala/issues/87#issuecomment-655294421

**Comment by pjfanning** [comment]
@mley I reread the issue you raised and the new behaviour seems correct to me. There is no easy way to make the BeanIntrospector parameterisable to allow it to optionally behave the old way. My recommendation would be that you create a DTO class that has no defaults. I use https://scalalandio.github.io/chimney/ in my day job a lot to do low boiler plate transforms between DTOs and internal model classes.

**Comment by pjfanning** [comment]
You can also use jackson [mixins](https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations). 

```
  val mapper = new ObjectMapper() with ScalaObjectMapper
  mapper.registerModule(DefaultScalaModule)
  mapper.addMixin[TestObject2, TestObject2Mixin]()
```

**Comment by mley** [comment]
Thanks for taking time to look into it, @pjfanning . In my opinion the behaviour is not correct, when the JSON value is set explicitly to null and the field is an `Option` type with a default value. In this case it never can get `None` when it's deserialized:

```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.scalatest.{FlatSpec, Matchers}

case class X(value: Option[String] = Some("value"))

class JacksonSpec extends FlatSpec with Matchers {

  val objectMapper = new ObjectMapper().registerModule(DefaultScalaModule)

  "X" should " be serialised and deserialised correctly" in {
    val x = X(None)
    objectMapper.readValue(objectMapper.writeValueAsString(x), classOf[X]) shouldBe x
  }
}
```

Just for the record if other people stumble up on this: I could restore the old behaviour by creating my own custom Scala Jackson module with a custom ScalaAnnotationIntrospectorModule that does not register the ValueInstantiator. (removed this line: https://github.com/FasterXML/jackson-module-scala/blob/913cdb9f35a5dc3d0ddd242247b16ad2f547e573/src/main/scala/com/fasterxml/jackson/module/scala/introspect/ScalaAnnotationIntrospectorModule.scala#L176 )

But we are not going that way. We will go with the new behaviour and try to avoid of default values.

**Comment by pjfanning** [comment]
You can also register a variant of DefaultScalaModule that doesn't include ScalaAnnotationIntrospectorModule
