### ISSUE TITLE
Will it be published to 2.10.5?

### ISSUE THREAD

**Issue by regadas** [FasterXML/jackson-module-scala#456]

**Comment by pjfanning** [comment]
There are zero changes in jackson-module-scala. Releases tend to happen when jackson-core and jackson-databind are released.

**Comment by regadas** [comment]
jackson-core was release for `2.10.5` and according to your comment this should be released to, no?

**Comment by pjfanning** [comment]
The release tickets get raised by @cowtowncoder when he thinks a new release is needed. It looks like he might have started a new release yesterday.

**Comment by cowtowncoder** [comment]
Yes, was about to file the issue, now there is #457
