### ISSUE TITLE
Deserializaition of an Option[] not failing on bad input, returning weird data instead. 

### ISSUE THREAD

**Issue by mdespriee** [FasterXML/jackson-module-scala#459]
Tested with version 2.11.1

```
case class Foo(value: Option[Long])

val mapper = new ObjectMapper() with ScalaObjectMapper
mapper.registerModule(DefaultScalaModule)
val json = """{ "value": "xx" }"""
val result = mapper.readValue[Foo](json) 
println(result.value) 
```
Instead of failing to deserialize the json (as it would occur without the option), it actually deserialize it and produces a weird object.
The println() outputs `Some(xx)` which does not make much sense for an Option[Long] ;-)
Using the debugger, I can see the actual runtime object in the Option is in fact a string.

**Comment by mdespriee** [comment]
Looks at bit like #382 but I'm not sure it's the exact same problem.

**Comment by pjfanning** [comment]
It is the same problem

**Comment by pjfanning** [comment]
closing due to https://github.com/FasterXML/jackson-module-scala/commit/1a1391b82e760e24c85a40933a39debe8c150fe5 -- this test seems to indicate that the upcoming 2.13.0 release handles this ok (with an InvalidFormatException)
