### ISSUE TITLE
Unable to deserailize Seq with AS_EMPTY null handling

### ISSUE THREAD

**Issue by nick-benoit14** [FasterXML/jackson-module-scala#462]
Configuring jackson to treat null collections as empty appears to work for java.util collections, but fails for scala collections like `Seq`
```
package com.centricient.service.bot

import java.util

import com.centricient.service.bot.JacksonTest.{D, E}
import com.fasterxml.jackson.annotation.{JsonSetter, Nulls}
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.junit.runner.RunWith
import org.scalatest.{BeforeAndAfter, FlatSpec, Matchers}
import org.scalatest.junit.JUnitRunner

import scala.collection.mutable


object JacksonTest {
  case class D(s: util.ArrayList[String])
  case class E(s: Seq[String])
}


@RunWith(classOf[JUnitRunner])
class JacksonTest extends FlatSpec with BeforeAndAfter with  Matchers {

  val mapper = new ObjectMapper()
  mapper.registerModule(new DefaultScalaModule());
  mapper.setDefaultSetterInfo(JsonSetter.Value.forValueNulls(Nulls.AS_EMPTY));

  it should "do stuff" in {

    val result1 = mapper.readValue("{\"s\": null}", classOf[D]) // Yields => D([])

    // Fails
    // com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot create empty instance of [collection-like type; class scala.collection.Seq, contains [simple type, class java.lang.String]], no default Creator
    // at [Source: (String)"{"s": null}"; line: 1, column: 7] (through reference chain: com.centricient.service.bot.JacksonTest$E["s"])
    val result2 = mapper.readValue("{\"s\": null}", classOf[E])

  }
}

**Comment by nick-benoit14** [comment]
Jackson version 2.10.4
Jackson Module Scala jackson-module-scala_2.12:2.10.4

**Comment by pjfanning** [comment]
scala 2.11 supports case class param default values - would it be possible to try `case class E(s: Seq[String] = Seq.empty)`

**Comment by nick-benoit14** [comment]
I get the same error with the default parameter

**Comment by pjfanning** [comment]
@cowtowncoder would you be able to provide some pointers on how to support a NullValueProvider. I tried extending the scala module Deserializer to implement the NullValueProvider but that didn't help. That code is in https://github.com/FasterXML/jackson-module-scala/pull/465

**Comment by cowtowncoder** [comment]
`NullValueProvider` interaction is indeed quite... elaborate, and probably the easiest way is to find counterparts in `jackson-databind` for similar handlers. I'll see if I can find suggestions for case you linked.

**Comment by cowtowncoder** [comment]
@pjfanning Not sure what specifically is failing, but to get "as-empty" handling, deserializer for type needs to first implement `getEmptyValue(DeserializationContext)`. If so, I think `src/main/java/com/fasterxml/jackson/databind/deser/impl/NullsAsEmptyProvider.java` should be usable as-is for scala types too.

Another place of interest might be `src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java` (method `_findNullProvider()`) -- depending on whether Scala deserializers extend it (in general it is recommendable to use it as the base for all deserializers), might be able to call that method.

Apologies for vague explanation: implementation is bit messy. But I think making `getEmptyValue(...)` work (if it does not already) would be a good first step.

**Comment by pjfanning** [comment]
@cowtowncoder thanks, I think I got it working

@nick-benoit14 could you try the latest 2.12.0-SNAPSHOT?

**Comment by pjfanning** [comment]
@cowtowncoder what is the v3.0.0 equivalent of
`mapper.setDefaultSetterInfo(JsonSetter.Value.forValueNulls(Nulls.AS_EMPTY))` ?

**Comment by cowtowncoder** [comment]
@pjfanning It is via `MapperBuilder`, from unit tests:

```
    public void testInjectWithCreator() throws Exception
    {
        ObjectMapper mapper = jsonMapperBuilder()
                .changeDefaultNullHandling(h -> JsonSetter.Value.construct(Nulls.AS_EMPTY, Nulls.AS_EMPTY))
                // ...
                .build();
    }
```

**Comment by pjfanning** [comment]
@cowtowncoder I copied over the new tests that work in 2.12 branch to the master branch but changed to use the changeDefaultNullHandling method you suggested. The tests fail. The getEmptyValue methods that I added don't appear to be called.

**Comment by cowtowncoder** [comment]
@pjfanning Sorry to hear that. Not sure what could be causing it unfortunately.
