### ISSUE TITLE
Release version 2.12.0-rc1 of Scala module

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#475]
The first rc release of Jackson 2.12 -- 2.12.0-rc1 -- is being released, current state of 2.12 being:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12

and would be great to get `jackson-module-scala` pre-release version out too.

Not sure if there will be rc2 or we go straight to 2.12.0; depends on what we find.

**Comment by pjfanning** [comment]
this is released

**Comment by cowtowncoder** [comment]
Thank you again @pjfanning !
