### ISSUE TITLE
Release version 2.12.0-rc2 of Scala module

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#477]
That time again: Jackson 2.12.0-rc2 -- the last release candidate for 2.12 unless some drastic problem is found -- is being released.

**Comment by pjfanning** [comment]
Should be in maven central soon.

I dropped support for scala 2.10 because the release was failing for that version and it is a very old scala release.

**Comment by cowtowncoder** [comment]
@pjfanning Ok thank you -- I will update 2.12 release notes to indicate dropping Scala 2.10 support then?

If not already mentioned, could you add a note on README about this as well?

**Comment by pjfanning** [comment]
@cowtowncoder https://github.com/FasterXML/jackson-module-scala/blob/master/release-notes/VERSION.md contains a note about java 8 and scala 2.11 being new minimum supported versions.

**Comment by cowtowncoder** [comment]
@pjfanning excellent, thank you again. I noted it on:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12

as well. Do you have modification access to that wiki? If so, feel free to update section on changes included; if not, let me know and I'll see if you need to be added to some group to give access.
