### ISSUE TITLE
Drop Scala 2.10 support

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#480]
(note: creating issue after the fact; Scala 2.10 support is being dropped from Jackson 2.12; no 2.12.0-rc2 was released -- but we need an issue to link to)

Jackson 2.12 will no longer support Scala 2.10 due to challenges in supporting this old version along with newer once; as well as low use (less than 2% of downloads via Maven Central).
This will probably mean that version definition in `jackson-bom`:

https://github.com/FasterXML/jackson-bom

should be left as latest 2.11 if not dropped altogether, as well.

**Comment by cowtowncoder** [comment]
@pjfanning Assigning to you just so you can modify description, add notes, link from release notes, as necessary.

I am also wondering about what to do with `jackson-bom` (as per above) -- will probably send a quick note on jackson-dev mailing list so we can decide what to do before 2.12.0 final (expected next weekend, in 8 days).

**Comment by pjfanning** [comment]
@cowtowncoder could we just remove this from the 2.12.0 bom?

```
      <dependency>
        <groupId>com.fasterxml.jackson.module</groupId>
        <artifactId>jackson-module-scala_2.10</artifactId>
        <version>${jackson.version.module.scala}</version>
      </dependency>
```

**Comment by cowtowncoder** [comment]
@pjfanning yes, great minds think alike etc :)

I sent a question on `jackson-dev`, and I think dropping that entry might be the best way to go, unless I hear good arguments for something else (like pointing to 2.11.3).

**Comment by cowtowncoder** [comment]
Removed the entry as discussed.
