### ISSUE TITLE
OptionDeserializer "should handle AS_NULL" test fails on JDK 15

### ISSUE THREAD

**Issue by SethTisue** [FasterXML/jackson-module-scala#487]
on both `master` and the `2.12` branch,  the following test fails on JDK 15

```
[info] An ObjectMapper with OptionDeserializer
...
[info] - should handle AS_NULL *** FAILED ***
[info]   com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot create empty instance of [simple type, class java.util.Optional<java.lang.String>], no default Creator
[info]  at [Source: (String)"{"o": null}"; line: 1, column: 1]
[info]   at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1766)
[info]   at com.fasterxml.jackson.databind.deser.std.StdDeserializer._findNullProvider(StdDeserializer.java:1897)
[info]   at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findValueNullProvider(StdDeserializer.java:1820)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase._resolveMergeAndNullSettings(BeanDeserializerBase.java:998)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:567)
[info]   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
[info]   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
[info]   at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:591)
[info]   ...
```

this turned up in the Scala community build: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1441/artifact/logs/jackson-module-scala-build.log

**Comment by SethTisue** [comment]
(maybe time to add `openjdk15` to your `.travis.yml`?)

**Comment by pjfanning** [comment]
Thanks @SethTisue - I just added that (just before your comment appeared - coincidentally). It might take me a few days to get around to debugging this issue, I'm afraid.

**Comment by SethTisue** [comment]
(no rush from my side, I can easily temporarily exclude the test from the community build)

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/commit/d4484db54d1984618b2dd0aa13cdc2c14e6e30e1 should hopefully fix the issue in the 2.12 branch

I will need to discuss the issue in the master branch with @cowtowncoder because the Jdk8Module should not be needed in master branch. The java Optional class should be supported by the main jackson-databind jar in the master branch. This is based on the documentation in https://github.com/FasterXML/jackson-modules-java8.

**Comment by cowtowncoder** [comment]
Java8 datatype module is embedded in `master`, and although not so with 2.12 there's possibility that maybe 2.13 could require Java 8 baseline and if so, likely would want to merge `Optional` support for that too, then.

**Comment by pjfanning** [comment]
@SethTisue I'm going to merge this with https://github.com/FasterXML/jackson-module-scala/issues/431 -- I've disabled a few of the master tests to that the 2.13 build should pass for master branch.
