### ISSUE TITLE
Rename/Work around Jackson 3.0 `Module`->`JacksonModule` renaming

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#499]
I did this:

https://github.com/FasterXML/jackson-databind/issues/3037

for Jackson 3.0 (master) but did not realize that name `JacksonModule` was in use in Scala module.
The reason to get out of `Module` name is due to addition of `java.lang.Module`, and seems reasonable. I hope Scala module can work around this problem either via imports or (if that makes more sense) renaming its `JacksonModule` into something else.

**Comment by pjfanning** [comment]
@cowtowncoder I've committed a workaround

**Comment by cowtowncoder** [comment]
Thank you!

There will be more renamings but I will try to tackle them if I can.

One next step is removal of (deprecated already in 3.0) of `Contextual[De]Serializer` interface.

**Comment by pjfanning** [comment]
@cowtowncoder Contextual[De]Serializer is still used a lot in jackson-module-scala - what is the alternative code?

**Comment by cowtowncoder** [comment]
@pjfanning Interfaces were merged into `JsonSerializer` / `JsonDeserializer` (with no-op implementation). Same is true for `Resolvable[De]Serializer`, likewise removed.
