### ISSUE TITLE
"Json[De]Serializer" -> "Value[De]Serializer" in 3.0

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#500]
Ok, so as per https://github.com/FasterXML/jackson-databind/issues/3044 I changed Scala module as well (with just mechanical search-and-replace), in `master`.

But it looks like I cannot re-compile with `sbt` for some reason. I suspect it might be due to some caching issue, but just in case I'll create this issue for someone else to have a look.
Hopefully it is just my system and this may be closed.

**Comment by pjfanning** [comment]
@cowtowncoder code is compiling - see https://travis-ci.com/github/FasterXML/jackson-module-scala/builds/216475652

**Comment by cowtowncoder** [comment]
Now I need to see what's up with local `sbt` but glad it's just some local issue. I did remove ivy cache (not sure that's used), tried `sbt cleanFiles` etc. But no doubt there's something like "sbt mrclean" or something :)

**Comment by pjfanning** [comment]
`sbt clean update`

-- this cleans build dir and updates the jar dependencies (useful when you have dependencies on snapshot jars)

**Comment by cowtowncoder** [comment]
Hmmh. I thought I tried "sbt update" too but... either I was hallucinating, or it has to be with "clean" as well.
Regardless, good to know, thanks!
