### ISSUE TITLE
Support Scala3  enums

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#501]
Currently supported in a separate module but eventually should be merged into this project.

https://github.com/pjfanning/jackson-module-scala3-enum

**Comment by gfZeng** [comment]
How's schedule?

**Comment by pjfanning** [comment]
Is there a reason not to use the library linked in the comment?

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/pull/660 is in jackson-module-scala 2.17.0
