### ISSUE TITLE
add Scala3 equivalent of ScalaObjectMapper

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#503]
ScalaObjectMapper is a mixin for Jackson ObjectMapper that provides some helper functions that use Scala Manifests to implicitly access type information.

Scala Manifests are not supported for Scala3.

The options would appear to be.
* write Scala3 macros
* use https://github.com/zio/izumi-reflect

**Comment by gaeljw** [comment]
I didn't look closely to the code yet but what do you use from `Manifest`s ?

If you need to access type parameters of a generic type, this is exactly the use case I'm currently dealing with in a library (Cucumber Scala) and after looking at izumi I built a minimal library to cover the need: https://github.com/gaeljw/typetrees.

Maybe you can grab some ideas there :shrug:  (Not saying you should use my library, I wouldn't be confident using it in such a big project as Jackson for now :sweat_smile:  )

**Comment by pjfanning** [comment]
@gaeljw the manifests are basically used here - https://github.com/FasterXML/jackson-module-scala/blob/2.12/src/main/scala/com/fasterxml/jackson/module/scala/ScalaObjectMapper.scala#L67

I see this as a convenience because in most cases, it's possible to use the Jackson ObjectMapper java methods directly and pass the type reference explicitly.

**Comment by gaeljw** [comment]
I've open a draft proposal without using macros at https://github.com/FasterXML/jackson-module-scala/pull/518 but I may be missing some stuff that make this proposal inadequate.

**Comment by gaeljw** [comment]
That's weird. I'll give it a look event though I'm not sure I have useful knowledge to understand such behaviour.

**Comment by pjfanning** [comment]
@gaeljw in https://github.com/FasterXML/jackson-module-scala/issues/522, I have added a comment with a link to a commit that disables the unit test that seems to cause the issue

**Comment by pjfanning** [comment]
jackson-module-scala 2.13.0-rc1 is released

**Comment by tnielens** [comment]
`scala.reflect.Manifest[T]` seems still supported by scala3. `TypeTag` not though. Wasn't `Manifest[T]` part of scala3 at the time of this issue creation? Could this library consider adding `ScalaObjectMapper` again?

**Comment by pjfanning** [comment]
@tnielens try doing a PR of your own - ScalaObjectMapper has never compiled under Scala 3 for me - we have ClassTagExtensions as a like for like replacement for ScalaObjectMapper and that works with Scala 3 (see the jackson-scala-module 2.13.0-rc2 release)

**Comment by tnielens** [comment]
My bad, indeed two level of nesting seems to be unsupported `List[GenericTestClass[Int]]`.

**Comment by gaeljw** [comment]
@tnielens the trait still exists but at compile time no value for the implicits instances will be provided by the compiler (or is it at runtime that there's an error? I don't remember exactly). But pretty sure that it doesn't work anymore and even if it works it's been deprecated since Scala 2.11, thus we should not rely on it.
