### ISSUE TITLE
investigate issues with master/jackson3 tests when scala 2.13.5 is used

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#504]
* 2.13 branch was ok after scala 2.13.5 upgrade
* 3 unit tests failed on master branch after scala 2.13.5 upgrade
  * https://travis-ci.com/github/FasterXML/jackson-module-scala/builds/217951510 
  * all affected tests seem to relate to param names that have dashes

**Comment by cowtowncoder** [comment]
Not sure if this is related, but `jackson-databind` in `master` has parameter name introspection built-in, whereas 2.x has it as separate `jackson-module-parameter-names` which Scala module tests might not register?

**Comment by pjfanning** [comment]
@cowtowncoder these tests are passing with latest jackson-databind and with scala 2.13.4 - upgrading to scala 2.13.5 breaks them. But things are very complicated because the jackson 2.13 codebase works fine with scala 2.13.5.

**Comment by pjfanning** [comment]
I added some really hack code to get the tests to pass again - the original fix caused more test failures than it fixed

* https://github.com/FasterXML/jackson-module-scala/commit/f589c8b4bbcfe6ff91059fff036ef729cbdc00fb
* https://github.com/FasterXML/jackson-module-scala/commit/223d77d0726ab62e7904d79f5f6d08112149db53
