### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0

### ISSUE THREAD

**Issue by behruz-b** [FasterXML/jackson-module-scala#513]
While migrating Play2  from 2.6 to 2.8.7 I've stuck with issue:

```
[error] com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error]         at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error]         at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:818)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4(JacksonObjectMapperProvider.scala:223)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4$adapted(JacksonObjectMapperProvider.scala:222)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.configureObjectMapperModules(JacksonObjectMapperProvider.scala:222)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.createObjectMapper(JacksonObjectMapperProvider.scala:246)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.create(JacksonObjectMapperProvider.scala:333)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.$anonfun$getOrCreate$1(JacksonObjectMapperProvider.scala:291)
[error]         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.getOrCreate(JacksonObjectMapperProvider.scala:291)
[error]         at akka.serialization.jackson.JacksonJsonSerializer.<init>(JacksonSerializer.scala:141)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
[error]         at scala.util.Success.flatMap(Try.scala:251)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:396)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:392)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error]         at scala.util.Failure.recoverWith(Try.scala:236)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:392)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:390)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error]         at scala.util.Failure.recoverWith(Try.scala:236)
[error]         at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
[error]         at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:424)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:862)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:370)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
[error]         at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:861)
[error]         at akka.serialization.Serialization.<init>(Serialization.scala:424)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
[error]         at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
[error]         at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1201)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1195)
[error]         at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1214)
[error]         at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1035)
[error]         at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
[error]         at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
[error]         at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:290)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:248)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```
I've tried to add different versions to dependency:
- `"com.fasterxml.jackson.core" % "jackson-databind" % "2.10.0"`
- `"com.fasterxml.jackson.core" % "jackson-databind" % "2.10.5.1"`

Before I hadn't add any dependencies of jackson-databind.

Please help to understand and solve the issue. Now server doesn't compile

**Comment by cowtowncoder** [comment]
Ok so: the exception message explains this all to you (although improvement suggestions always welcome).

Jackson-module-scala depends on `jackson-databind` (and that depends on `jackson-core` (streaming parser/generator) and `jackson-annotations`). So regardless of whether you add a dependency, module must have it -- module simply adds support for Scala-specific aspects, value types. Databind package does most work converting between token stream (parsed/generated by core).

Due to a very common problem of users accidentally using incompatible minor versions of Scala module and databind (which you have bumped into too, possibly!), module author added a check at some point to help prevent this root cause.
Without the check it is possible that incompatibilities between minor versions caused problems (specifically if the databind version is older than module; the other way around should be backwards compatible).

So what you need to do is to ensure that minor versions match, which is what you are doing.

If code does not compile, well, it would be much easier to help if you added some information of what is failing and how...

**Comment by pjfanning** [comment]
This is not a jackson-module-scala bug.

You need to have consistent jackson versions on your classpath.

If you use sbt, use `sbt dependencyTree` to get a printout of your dependencies.

**Comment by pjfanning** [comment]
I added this to v2.13 branch - https://github.com/FasterXML/jackson-module-scala/commit/e4b6bb4668dca0dcb0eb2854116bc0076f106137 -- I corrected the typo in `version` already

**Comment by cowtowncoder** [comment]
One thing we might control, and that I may have mentioned previously is that a relaxed check could allow newer minor versions of `jackson-databind`; possibly at least the immediately adjacent one.
Not sure how useful that possibility is (or a configuration toggle to simply force use of whatever is available) but thought worth mentioning again.

**Comment by pjfanning** [comment]
@cowtowncoder I don't think you can keep everyone happy - if we don't insist that the jackson versions match, we will get a large number of people complaining about errors that turn out to be caused by them using mismatched versions of jackson jars.

**Comment by cowtowncoder** [comment]
Quite true.

I am just trying to think out aloud of how things should develop for Jackson framework as whole: Scala module is the only module currently verifying version metadata and maybe other modules could start doing something similar.
But the check itself is stricter than it absolutely has to be: the actual rule is that whatever you depend on must have at least same minor version. There is no real requirement to check that it could not have higher minor version, however: 2.x is designed to try to allow higher dependency versions.
At the same time the recommendation of course is to match all minor versions. This mostly becomes challenging with non-Fasterxml components like BSON and MsgPack format modules (which either sporadically release versions, or use their own versioning scheme).

I am fine leaving the check as-is, with whatever is deemed suitable wording.

**Comment by behruz-b** [comment]
I've added following library and it starts compiling:
`"com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.12.2"`

Thanks

**Comment by ertra** [comment]
Hello,

I would like to ask a I am getting similar error.

While upgrading from Play 2.7.9 to 2.8.8 and using scribejava (see its dependencies https://github.com/scribejava/scribejava/blob/master/pom.xml), I am now getting this error

`[error] com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.11.4 requires Jackson Databind version >= 2.11.0 and < 2.12.0`

the scribejava is adding to classpath newer version of com.fasterxml.jackson.databind - version 2.12.3

I am getting the error, whan I run my app. (not during compile)

I am using this in my build.sbt to go over it, to use older jackson:

dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-databind" % "2.11.4"
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-core" % "2.11.4"

but I am not sure , if this is the right "fix".

please can you point me to the right solution.

regards
tomas zeman

**Comment by cowtowncoder** [comment]
This is a closed issue and it's not a good idea to tag along those.

But as to the error, it does what it says: Scala module does require matching minor version of `jackson-databind`. So you should either use newer Scala module (2.12.5) or downgrade all the other components (like you do).

**Comment by mkurz** [comment]
For anyone wanting to upgrade Jackson in Play 2.8 have a look here: https://github.com/playframework/playframework/discussions/11222

**Comment by rohithvangapalli** [comment]
> 

It really helped
