### ISSUE TITLE
serialize case object style enum to String

### ISSUE THREAD

**Issue by xyting** [FasterXML/jackson-module-scala#515]
I using `case object` to define `enum`, assume as the following codes:

```scala
sealed trait RuleState 
object RuleState {
  case object ACTIVE extends RuleState
  case object PAUSE extends RuleState
  case object DELETE extends RuleState
  case object CONTROL extends RuleState
}
```

```scala
case class Rule(name:String, state: RuleState)
```

Has any solution to serialize `Rule` to json and deserialize back to `Rule`?

```json
{
    "name": "test",
    "state": "ACTIVE"
}
```

**Comment by pjfanning** [comment]
have you tried to test this?

**Comment by pjfanning** [comment]
Some pointers if this doesn't work (I think serialization might but that deserialization might not)
* you could write custom jackson serializer/deserializer for your class (eg https://www.baeldung.com/jackson-custom-serialization)
* you could use a Scala enumeration (https://www.scala-lang.org/api/current/scala/Enumeration.html) - this is supported by jackson-module-scala
*  you could use enumeratum (https://github.com/lloydmeta/enumeratum) - this is not supported by jackson-module-scala but https://github.com/pjfanning/jackson-module-enumeratum might help

**Comment by xyting** [comment]
I had using custom jackson serializer/deserializer to solution this, I only inquisitive whether have any better or simple ideas
