### ISSUE TITLE
Non-empty collection deserializer module

### ISSUE THREAD

**Issue by a1kemist** [FasterXML/jackson-module-scala#517]
I'm not sure if this belongs here, but I was wondering how a non-empty collection deserializer module could be implemented?

Essentially I'm in the process of trying to implement a jackson module for [typelevel/cats](https://github.com/typelevel/cats) data types, specifically [NonEmptyList](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/data/NonEmptyList.scala). 

I would expect that
```scala
NonEmptyList.of("cat", "bat", "ball")
```
would serialize as
```json
["cat","bat","ball"]
```
and deserialize as
```scala
NonEmptyList("cat", List("bat", "ball"))
```

Looking at the `SeqDeserializerModule`, I've been able to get most of the bits together, but I'm unsure how to enforce that there is always atleast one element in the json array.

Am I just missing something in jackson core that would help with this?

**Comment by pjfanning** [comment]
I think it best that we don't add a cats dependency to jackson-module-scala and that this code stays in its own project.

Won't cats fail if you try to create a NonEmptyList with no elements? Isn't that enough? Your cats deserializer could check if the data is empty before trying to create the NonEmptyList and raise a human readable error.

I can't see it being the job of jackson-core/jackson-databind to somehow be aware of this.

**Comment by a1kemist** [comment]
My apologies if it seemed that I had intended to add a cats dependency, that was not the case. This was more of an implementation question rather than an issue (is there a mailing list or gitter for these sorts of things?).

You are right that it will fail to create a NonEmptyList with no elements, but there isn't a default constructor like there is for Iterable types (because that would invalidate the NonEmpty-ness). So far looking at `GenericFactoryDeserializerResolver`, it sets up the `Deserializer` using an `Instantiator` with `createUsingDefault` and `canCreateUsingDefault` set to true. This works fine for iterables and the standard library collections because you can always start with an empty collection/mutable builder, but doesn't work for non-empty types.

I was hoping that I could disable `canCreateUsingDefault`, but it sounds like you are suggesting that instead I utilize the underlying type (List, Vector, etc) and then handle throwing the exception after calling `containerDeserializer.deserialize` in the `Deserializer`?

**Comment by pjfanning** [comment]
I'm afraid I'm only making high level suggestions. I'm afraid I'm going to have to leave it to you to work it out. If I was writing this, I would not use GenericFactoryDeserializerResolver as my template - that is an attempt to handle many iterable types - you are trying to handle 1 type (eg something more like OptionDeserializerModule)

**Comment by cowtowncoder** [comment]
It makes sense to see what might be available from jackson-databind side, but @pjfanning is correct in that there isn't much support for validating contents: deserializers are responsible for enforcing most limitations.

For registering  deserializers one thing to note is that if generic types are needed (which I think is true in this case), avoid `SimpleModule` (and in general `SimpleXxx` types) as they are for handlers of non-generic types. General `Module` type allows registering various things, and the interface for registering deserializers via callback style access is `Deserializers`; latter gets full `JavaType` for which deserializer is needed.
