### ISSUE TITLE
Scala 3 Support for Jackson 2.9?

### ISSUE THREAD

**Issue by AugustNagro** [FasterXML/jackson-module-scala#520]
Hi,

Is there any interest in publishing Scala 3 support for older Jackson versions? I'm unfortunately stuck on version 2.9.10, and the lowest required version is 2.13.0.

**Comment by pjfanning** [comment]
Considerable changes were needed to be made for Scala 3 support - these will not be backported to such an old version.

**Comment by AugustNagro** [comment]
Ok, sounds good :+1:
