### ISSUE TITLE
investigate why travis no longer builds the module

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#524]
https://travis-ci.com/github/FasterXML/jackson-module-scala/requests?requestId=570622305

for last 15 days, all builds fail to start saying they are unauthorised

@cowtowncoder would you know why this is the case? Has fasterxml exceeded the number of credits for the account?

**Comment by cowtowncoder** [comment]
I just noticed this by note from Kotlin module author; it does look like no builds have been done for past 2 weeks like you say.
I did not even know of credits: builds are under free account so perhaps limits have been tightened or something.

**Comment by pjfanning** [comment]
@cowtowncoder travis-ci.org has recently transitioned to travis-ci.com and I think that open source projects may be limited in the number of build credits now

**Comment by cowtowncoder** [comment]
Yes, I knew about transition (and did check). Looks like free account I have has 10,000 credits / month, but I don't know where to check for actual balance yet. Seems plausible that we've run out.

Consensus seems to be that perhaps Github Actions would be a better way; the main concern I'd have is just that of how to auto-publish snapshot builds.

All in all, I really despise Bitcoin Miners (assholes) that abuse freely available CI/CD systems. This is what we get as a result. :-(

**Comment by cowtowncoder** [comment]
One thing I just did was to select the plan (Free Plan) so that I can actually see the credits available.
That alone did not appear to solve the issue but I assume it was one blocker.

**Comment by cowtowncoder** [comment]
Ah. But I ALSO need to enable it for FasterXML accounts (initially only changes for my personal one).

Now builds for `jackson-databind` trigger.

**Comment by pjfanning** [comment]
@cowtowncoder travis builds for jackson-module-scala are now working again
