### ISSUE TITLE
investigate issue with introspecting private fields in Scala 3

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#534]
Passes with Scala 2.

* https://github.com/FasterXML/jackson-module-scala/blob/master/src/test/scala-2.%2B/com/fasterxml/jackson/module/scala/introspect/BeanIntrospectorScala2Test.scala

**Comment by smarter** [comment]
A private val that is not referenced anywhere in a class will not become a field in scala 3 but just a local variable in the class constructor. Add a method to the class that references the field and the test will probably pass.

**Comment by pjfanning** [comment]
Thanks @smarter - you are correct, this is only really an issue if the class only declares the variable and then does not use it - doesn't really appear to be an important use case for jackson-module-scala to support.

I have added test cases like the ones you suggested and they pass. I will close this.
