### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by SauravK1996** [FasterXML/jackson-module-scala#544]
(run-main-0) java.lang.VerifyError: class org.apache.spark.sql.catalyst.plans.logical.UpdateAction overrides final method children.()Lscala/collection/Seq;

**Comment by pjfanning** [comment]
Apologies but we don't provide spark support and this is not a reproducible test case. I would suggest getting together a reproducible test case and trying stackoverflow or a spark users mailing list
