### ISSUE TITLE
In progress Jackson release process can break builds depending on latest version

### ISSUE THREAD

**Issue by jonatan-ivanov** [FasterXML/jackson-module-scala#548]
I'm not familiar with the release process of Jackson but I assume it can take a while.
During this process builds depending on Jackson can break due to already published modules depending on unpublished ones.

E.g.: let's say we have a project that depends on `jackson-module-abc` which depends on `jackson-module-xyz`. If the release process publishes `jackson-module-abc` first our build will fail till `jackson-module-xyz` is published. If the publishing order is the opposite, there would be no problems.

To give a more realistic example: if the bom is published first, whoever consumes the bom can be broken until the other modules are published:
```
> Could not find com.fasterxml.jackson.module:jackson-module-scala_2.13:2.13.0.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.13/2.13.0/jackson-module-scala_2.13-2.13.0.pom
    - file:/Users/jivanov/.m2/repository/com/fasterxml/jackson/module/jackson-module-scala_2.13/2.13.0/jackson-module-scala_2.13-2.13.0.pom
  Required by:
      project :micrometer-samples-core > project :micrometer-registry-stackdriver > com.fasterxml.jackson.core:jackson-databind:2.13.0 > com.fasterxml.jackson:jackson-bom:2.13.0
```
(full error message: https://ge.micrometer.io/s/vywlbquulkvdc/failure#1)
I don't think this is a huge issue but we bump into this at ~every jackson release with micrometer.

(I wanted to open this under https://github.com/FasterXML/jackson but the description asked me not to so I opened it here because this is the module I encountered this issue with, please move it if it is not appropriate.)

**Comment by pjfanning** [comment]
I don't understand your build process but the jackson release takes a while as there are many modules. Why do you need to use jackson 2.13.0 within hours of its release?

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/issues/547#issuecomment-931955303

**Comment by cowtowncoder** [comment]
@jonatan-ivanov Realistically it is what it is -- yes, there is a window of incompatibility as Maven publishing cannot really be made atomic across all components.
I also echo @pjfanning's sentiment about jumping to latest version: yes, it is unfortunate there is the delay but at the same time, users would be well advised to have an idea of the version set they are upgrading to. We can try to figure out better ways for communication.

**Comment by jonatan-ivanov** [comment]
@pjfanning In the `main` branch of micrometer, we are depending on `latest.release` or latest patch versions of our dependencies whenever we can. This means that we always use the latest versions and always test against the latest bits "for free", we don't need to update everything manually. When we cut a new release, we lock dependency versions (so that build is reproducible) and only update as needed.  
We don't need to use jackson within hours of its release but build systems do not have a `latest.release.older-than-1d` so we use what they offer: `latest.release`.

@cowtowncoder I think an improvement could be publishing in a more optimal order (e.g.: bom should be published last) but I have no idea how hard this is, probably does not worth the hassle. You can close the issue, I just wanted to raise this and ask our opinion. As I said I don't think this is a huge issue, we just bump into it more frequently with jackson because of the longer release process.

**Comment by pjfanning** [comment]
Many people use features like dependabot. This means you have a definite build dependency in your build so you are not affected by new versions of dependencies being published but dependabot will create a PR automatically for the dependency update and this will be tested in its own PR build. This is the approach I rely on in my projects.

**Comment by jonatan-ivanov** [comment]
Yeah dependabot can totally solve this issue by having less frequent updates and also separating the update on a PR till the issue gets resolved. This only works though for those who can use dependabot. Micrometer could but I guess some users can't (they may able to use dependency locking and update the locks on a scheduled basis).

**Comment by cowtowncoder** [comment]
@jonatan-ivanov I 100% agree that ideally BOM would be released afterwards when all (if possible, or most at any rate) components were published.
Unfortunately `jackson-bom`/`jackson-base` itself is used by many Jackson components being released, so there is essentially a cyclic dependency. So as of now I do not have a good idea of how to untangle this -- 
This was the context of my "for now this may be how things are" comment. Not that I did not think this is problematic.

**Comment by jonatan-ivanov** [comment]
👍🏼 Thank both of you for looking into this. We can utilize dependabot/lock dependencies for our `main` branch or bite the bullet, being on the bleeding edge means bleeding sometimes after all. :D

I think we should close this issue, please reopen/transfer and ping me if you figured something out, I'm curious.
