### ISSUE TITLE
Use DefaultScalaModule with Java?

### ISSUE THREAD

**Issue by erikv85** [FasterXML/jackson-module-scala#567]
Can DefaultScalaModule be used with Java? If so, what are the necessary libraries to include?

```
$ jshell --class-path module/jackson-module-scala_2.13/2.13.1/jackson-module-scala_2.13-2.13.1.jar:core/jackson-databind/2.13.1/jackson-databind-2.13.1.jar:core/jackson-core/2.13.1/jackson-core-2.13.1.jar
|  Welcome to JShell -- Version 17.0.1
|  For an introduction type: /help intro
jshell> import com.fasterxml.jackson.databind.json.JsonMapper
jshell> import com.fasterxml.jackson.module.scala.DefaultScalaModule
jshell> var mapper = JsonMapper.builder().addModule(DefaultScalaModule).build()
|  Error:
|  cannot find symbol
|    symbol:   variable DefaultScalaModule
|  var mapper = JsonMapper.builder().addModule(DefaultScalaModule).build();
|                                              ^----------------^
```

**Comment by pjfanning** [comment]
that is the right jar - please talk to jshell experts about how to debug jshell issues

**Comment by erikv85** [comment]
> that is the right jar - please talk to jshell experts about how to debug jshell issues

Thanks, but I'm also having problems compiling.

```
$ cat << EOF >> ScalaJackson.java
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.module.scala.DefaultScalaModule;
public class ScalaJackson {
    public static void main(String[] args) {
        var mapper = JsonMapper.builder().addModule(DefaultScalaModule).build();
    }
}
EOF
$ javac -cp module/jackson-module-scala_2.13/2.13.1/jackson-module-scala_2.13-2.13.1.jar:core/jackson-databind/2.13.1/jackson-databind-2.13.1.jar:core/jackson-core/2.13.1/jackson-core-2.13.1.jar ScalaJackson.java
ScalaJackson.java:5: error: cannot find symbol
        var mapper = JsonMapper.builder().addModule(DefaultScalaModule).build();
                                                    ^
  symbol:   variable DefaultScalaModule
  location: class ScalaJackson
1 error
```

**Comment by pjfanning** [comment]
I'm afraid this is not a jshell debug support service - it is for reporting specific issues with this project

**Comment by erikv85** [comment]
It's not jshell specific, see https://github.com/FasterXML/jackson-module-scala/issues/567#issuecomment-1030633023.

**Comment by pjfanning** [comment]
please use a build tool like gradle or maven - that bring in transitive dependencies

please explain how this compile issue is the fault of the jackson-module-scala team

**Comment by plokhotnyuk** [comment]
@erikv85 Have you tried `DefaultScalaModule$.MODULE$` yet?

**Comment by pjfanning** [comment]
thanks @plokhotnyuk  - I added https://github.com/FasterXML/jackson-module-scala/commit/680af768a76c9e35a12626d7660c5f54fc095a7c to document this

**Comment by erikv85** [comment]
@plokhotnyuk Thanks, I wasn't aware of that. Works fine now of course.
@pjfanning Thanks for adding the description, this can be closed now.
