### ISSUE TITLE
Integer in Double field causes ClassCastException

### ISSUE THREAD

**Issue by charpov** [FasterXML/jackson-module-scala#571]
This small Scala 3 example:
```scala
case class Time(time: Option[Double])

@main def TestJson() =
   val mapper  = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions
   val str     = """{"time": 20}"""
   val q: Time = mapper.readValue(str)
   println(q)
   println(q.time.forall(_ > 0.0))
```
triggers a `ClassCastException` on the last line.
It looks like when `forall` unwraps the double value, it finds an integer.
If the Json source uses 20.0 instead, everything works fine.

**Comment by pjfanning** [comment]
This is a known issue - documented in https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-seqint-and-other-primitive-challenges

**Comment by pjfanning** [comment]
duplicates https://github.com/FasterXML/jackson-module-scala/issues/275

**Comment by charpov** [comment]
Thanks for the quick response and the pointer to the FAQ, with possible workarounds.  Reflection in Scala has always been messy (and the changes from 2 to 3 don't help).  I think using `java.lang.Integer` and `java.lang.Double` in my types will make a quick and workable fix.
