### ISSUE TITLE
change group Id to tools.jackson and scala packages also (jackson v3 only)

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#583]
anywhere where com.fasterxml.jackson appears will become tools.jackson - other jackson libs will change too

does not affect the v2.x releases - jackson v3 is not due for GA release for quite some time

**Comment by pjfanning** [comment]
publishing to https://s01.oss.sonatype.org/content/repositories/snapshots/tools/jackson/module/ works now

**Comment by cowtowncoder** [comment]
Great!
