### ISSUE TITLE
Unable to use registerReferencedType on Option with default value None

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [FasterXML/jackson-module-scala#598]
With the following scala case classes : 

```
final case class NestedLong(var id: Option[Long] = None)
final case class ParentWithNested(var nested: NestedLong)
```

When deserializing this, we obtain an `Integer` instead of a `Long` in the `id` field.
As stated in the [FAQ](https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#jackson-2131), we used the following sentence to give the correct Option primitive type on deserialize : 
`ScalaAnnotationIntrospectorModule.registerReferencedValueType(classOf[NestedLong], "id", classOf[Long])`

However, it seems that it doesn't work when the option have an initialization value set to None.
The same model without initialization works : 
```
final case class NestedLong(var id: Option[Long])
final case class ParentWithNested(var nested: NestedLong)
```

Yours faithfully,
LCDP

**Comment by pjfanning** [comment]
I didn't see this and raised https://github.com/FasterXML/jackson-module-scala/issues/599 - the latter has commits based on it - so I'll close this as the duplicate
