### ISSUE TITLE
ScalaAnnotationIntrospectorModule.registerReferencedValueType doesn't work properly when fields have default values

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#599]
One of the issues causing https://github.com/pjfanning/jackson-scala-reflect-extensions/issues/5 - see also https://github.com/FasterXML/jackson-module-scala/issues/598

**Comment by pjfanning** [comment]
Fix is in the v2.13.4 release

**Comment by AntoineDuComptoirDesPharmacies** [comment]
@pjfanning 
v2.13.4 is working like a charm, thank you !
