### ISSUE TITLE
Case Classes with Option[Long] parameters don't deserialize properly

### ISSUE THREAD

**Issue by kscaldef** [FasterXML/jackson-module-scala#62]
It seems that for small numbers, an Option[Long] in a case class actually gets deserialized with a runtime type of int.  This can then manifest in a couple ways.  Maps using these values as keys may not behave as expected, and conversions to Java Longs will throw a ClassCastException:

```
[info]   java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
[info]   at scala.runtime.BoxesRunTime.unboxToLong(Unknown Source)
```

This only seems to affect case classes.  Option[Long] by itself seems to behave correctly.

**Comment by eugeniyk** [comment]
What is the workaround if your case class is generated for you? I don't have an access to apply attribute.

**Comment by devshorts** [comment]
@christophercurrie is it possible to create an optional module that uses what finatra has to work around this? It looks like they use the scala signature parsing https://github.com/twitter/finatra/tree/develop/jackson/src/main/scala/com/twitter/finatra/json/internal/caseclass/jackson

Having to annotate works fine, but its problematic when you are trying to distribute a model class (for example) which now pulls in all of jackson databind.  Had the annotation been in jackson-annotations it would be less problematic, but leaking a dependency like that really sucks.

I'd be really open to having a separate module (if we don't want to include that in the main one) that provided for option[long] parsing via signature parsing in the interim, until the deprecation comes around for 2.10>
