### ISSUE TITLE
Serialization not working properly for map of sealed traits with JsonSubTypes and JsonTypeInfo annotated

### ISSUE THREAD

**Issue by garrychnca** [FasterXML/jackson-module-scala#623]
Hi I am opening this issue because I tried filtering existing ones with keyword `map`, `sealed trait` but couldn't find anything relevant.

## Versions

scala: 2.12.15
jackson-module-scala: 2.12.2

## Summary

With a sealed trait (`@JsonSubTypes` and `@JsonTypeInfo` annotated) and some subclasses, serializing (`writeValueAsString`) of individual object of the sealed trait works as expected, however, serializing of Scala map of string to the sealed trait does not work as expected.

## UT Code Illustrating the Problem

```scala
package some.playground

import com.fasterxml.jackson.annotation.JsonSubTypes.Type
import com.fasterxml.jackson.annotation.JsonTypeInfo.{As, Id}
import com.fasterxml.jackson.annotation.{JsonSubTypes, JsonTypeInfo}
import com.fasterxml.jackson.databind.json.JsonMapper
import com.fasterxml.jackson.module.scala.{ClassTagExtensions, DefaultScalaModule}
import org.scalatest.flatspec.AnyFlatSpec

class JsonMapperTest extends AnyFlatSpec {
    val jsonMapper: JsonMapper = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions
    val goldenRetriever: Dog = Dog("Golden Retriever")
    val devonRex: Cat = Cat("Devon Rex")

    @JsonSubTypes(value =
        Array(
            new Type(value = classOf[Dog], name = "dog"),
            new Type(value = classOf[Cat], name = "cat")
        )
    )
    @JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "__type")
    sealed trait Animal

    case class Dog(breed: String) extends Animal

    case class Cat(breed: String) extends Animal

    "single value" should "serialize successfully" in {
        // expected and succeeded
        assert(
            jsonMapper.writeValueAsString(goldenRetriever) == """{"__type":"dog","breed":"Golden Retriever"}"""
        )

        // expected and succeeded
        assert(
            jsonMapper.writeValueAsString(devonRex) == """{"__type":"cat","breed":"Devon Rex"}"""
        )
    }

    "map values" should "serialize successfully" in {
        val map: Map[String, Animal] = Map("a" -> goldenRetriever, "b" -> devonRex)

        // UNEXPECTED but succeeded
        assert(
            jsonMapper.writeValueAsString(
                map
            ) == """{"a":{"breed":"Golden Retriever"},"b":{"breed":"Devon Rex"}}"""
        )

        // expected but failed
        assert(
            jsonMapper.writeValueAsString(
                map
            ) == """{"a":{"__type":"dog","breed":"Golden Retriever"},"b":{"__type":"cat","breed":"Devon Rex"}}"""
        )
    }
}
```

**Comment by pjfanning** [comment]
* there is https://github.com/pjfanning/jackson-scala-reflect-extensions
* why are you using such an old version of Jackson?
* v2.15.0 is about to be released and I don't want to look at any changes until that is safely released

I don't want to add more Java or Scala reflection based code in this module - as it is complicated enough already.

If you don't like https://github.com/pjfanning/jackson-scala-reflect-extensions, you could try writing a patch for this module but I would be reluctant to accept anything that increases the number of dependencies.

**Comment by garrychnca** [comment]
Hi @pjfanning thanks for the response.

Unfortunately I have no control over what version of this lib I can use and 2.12.2 is the latest version (internally).

Thanks for pointing to the scala reflect extensions. Let me quickly check if it solves my problem.

**Comment by garrychnca** [comment]
I did a quick check and the reflect lib you mentioned does not exist internally.

Going back to the original question, is it expected that map of sealed trait won't be serialized with annotated type information? Or it is pending investigation until v2.15.0 is released?

**Comment by pjfanning** [comment]
I'm not planning on spending any time on this. Map[A, B] is not a good way to represent data when it comes to Jackson. Type erasure occurs and it is very hard to work around that. Jackson relies on Runtime Reflection.
Try one Circe or some Scala specific JSON framework. Scala specific frameworks can use implicits and/or macro to grab the type info at compile time.

**Comment by garrychnca** [comment]
Got it, thank you for the information.

Given what you said pleas feel free to close this issue.

**Comment by pjfanning** [comment]
I created https://github.com/FasterXML/jackson-databind/pull/3833 which I think the demos this Map issue as a general jackson-databind issue as opposed to being specifically an issue with this Scala module.

**Comment by pjfanning** [comment]
@garrychnca could you have a look at the AnimalMap class that I created in https://github.com/FasterXML/jackson-databind/pull/3833 - it is one way that you can. work around the issue. I know this is Java but Jackson is a Java lib with Scala support added and it is likely that an equivalent Scala based AnimalMap will succeed (the most important aspect is getting the JsonType annotation on the map declaration).

**Comment by cowtowncoder** [comment]
FWTW, that issue is not something can be resolved automatically: Java Type Erasure prevents access to generic type information that would be needed for polymorphic handling on value types. This can be solved by developer with one of work-arounds I noticed in issue @pjfanning referenced -- I would generally recommend use of wrapper value object (so root value is never generic) but there are others.

**Comment by garrychnca** [comment]
Hey @pjfanning and @cowtowncoder,

Thank you so much for following up with this issue here. I checked your explanations and they make sense to me.

In fact, in my scenario I do only use this with POJO instead of maps. I only encountered this issue during unit testing the ser/deser of the classes.
