### ISSUE TITLE
case class was incorrectly deserialized as a Map

### ISSUE THREAD

**Issue by impasse** [FasterXML/jackson-module-scala#626]
```scala
@main
def test(): Unit = {
  val mapper: JsonMapper = JsonMapper.builder()
    .addModule(DefaultScalaModule)
    .enable(DeserializationFeature.USE_JAVA_ARRAY_FOR_JSON_ARRAY)
    .build()
  
  case class I(i: Int)
  case class W(b: List[I])
  val d = mapper.readValue[W](
    """
      |{ "b": [ { "i": 1 }, { "i": 2 } ] }
      |""".stripMargin, classOf[W])
  println(d.b.head.i)
}
```

As in the example above, the result of deserialization `d.b` is a `List[Map]`, not a `List[I]`.

**Comment by pjfanning** [comment]
what happens if you remove `.enable(DeserializationFeature.USE_JAVA_ARRAY_FOR_JSON_ARRAY)`?

**Comment by impasse** [comment]
The result is still the same, List[Map].

**Comment by pjfanning** [comment]
I see you are using Int - and type erasure makes that very hard to support.

Please read https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-seqint-and-other-primitive-challenges

**Comment by impasse** [comment]
```scala
import com.fasterxml.jackson.databind.json.JsonMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule

@main
def test(): Unit = {
  val mapper: JsonMapper = JsonMapper.builder()
    .addModule(DefaultScalaModule)
    .build()
  
  case class I(i: Option[Int])
  case class W(b: List[I])
  val d = mapper.readValue[W](
    """
      |{ "b": [ { "i": 1 }, { "i": 2 } ] }
      |""".stripMargin, classOf[W])
  println(d.b.head.i)
}
```
But when I replaced it with `Option[Int]`, it's still the same `List[Map]`:
`class scala.collection.immutable.Map$Map1 cannot be cast to class test$package$I$1`

**Comment by impasse** [comment]
Okay, I'm just giving feedback on this issue. It doesn't affect my usage at the moment.

**Comment by pjfanning** [comment]
I added https://github.com/FasterXML/jackson-module-scala/commit/6441dd9680de27c1ee3c36d1160606a488c09faf and the test seems to work ok - maybe I'm missing something
