### ISSUE TITLE
investigate major binary compatibility regressions caused by jackson-databind 2.15.0-rc3-SNAPSHOT

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#630]
See https://github.com/FasterXML/jackson-module-scala/actions/runs/4657473214/jobs/8242103815

* jackson-module-scala tries to maintain binary compatibility between releases and uses a build tool to check for this
* I switched dependency from jackson-databind v2.15.0-rc2 to v2.15.0-rc3-SNAPSHOT and found over 30 new binary compatibility issues relating to code deprecations
* this is not something that I've seen before and I will need to spend time working out what to do
* the issues appear to be because of changes in jackson-databind AnnotationIntrospector or related classes

@cowtowncoder Can you delay v2.15.0-rc3 release until I get to the bottom of this? The issue appears to be caused by https://github.com/FasterXML/jackson-databind/commit/7161d21b9451773f6d7ecfcd9a16d857663176b5 and there is probably no need to revert that - I probably just need to add some build config to ignore the binary compatibility issues

**Comment by pjfanning** [comment]
I fixed the build issue with hhttps://github.com/FasterXML/jackson-module-scala/commit/ae65569ce11dae82686adbb97d0e17f81d925651

**Comment by cowtowncoder** [comment]
@pjfanning Ok sorry about that. I had assumed that all modules would have long ago switched not to use those methods -- and also rebuilt core modules. But I forgot that I do not do this for Scala module.

And I should also know better than to start cleanup after second release candidate. In future I will postpone these appropriately.

Thank you for catching this so quickly.

**Comment by pjfanning** [comment]
It's not that we use the methods. The build checks for API changes and when we subclass, the build will fail if methods are removed in the super classes. These checks can be configured to ignore certain diffs and I've now done that.

**Comment by cowtowncoder** [comment]
Ok good. Kotlin module does something similar, makes sense.

Might make sense for databind too, although one concern I have is with sheer number of overrides needed for "internal" changes (in theory any change to any `protected` methods is backwards-incompatible change). The idea is valid tho, it is important to be aware of such changes to avoid accidental removal/change of methods.
