### ISSUE TITLE
Update 2.15 release notes with Scala changes

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#633]
It'd be great to get Scala fixes, improvements etc on:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15

under "Changes, JVM Languages" section. I will add ones from release notes, but if you could double-check @pjfanning that'd be great.

**Comment by pjfanning** [comment]
those are the only headline changes in 2.15.0

**Comment by cowtowncoder** [comment]
@pjfanning Thanks! I wasn't sure since I've seen so many updates, thank you for confirming.
