### ISSUE TITLE
Update `2.17` branch to `2.17.0-rc1-SNAPSHOT`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#667]
As we are getting closer to 2.17 release candidates, I am changing version for 2.17 branch repos to `2.17.0-rc1-SNAPSHOT` (with jackson-bom already being updated).
So would be good to get Scala module updated too.

**Comment by pjfanning** [comment]
done

**Comment by cowtowncoder** [comment]
Thanks!
