### ISSUE TITLE
Update 2.17 release note wiki with Scala module 2.17 fixes

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#673]
I realized that Scala fixes for 2.17 are not yet included on:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.17

but it'd be great to get those (looks like there are .... 2? from release notes). Might increase total improvement count over 100 :)

**Comment by pjfanning** [comment]
For reference, the jackson-module-scala release notes are maintained separately at https://github.com/FasterXML/jackson-module-scala/blob/2.18/release-notes/VERSION.md

I've added the 2.17.0 specific changes to the Jackson wiki but in practice, the Scala changes are rarely added to that wiki.

**Comment by cowtowncoder** [comment]
Thank you. Yes, I'll need to get in practice of copying these (or linking to) as part of release process. For other modules it's easier as I modify entries when closing issues, as part of merging the fix. For ones I don't maintain (Scala and Kotlin specifically) this won't work so just need to figure out simplest, low-maintenance way of keeping track of changes.

**Comment by pjfanning** [comment]
Would it be possible to just link to https://github.com/FasterXML/jackson-module-scala/blob/2.18/release-notes/VERSION.md or its version specific branch?

I prefer maintaining one source of truth.
