### ISSUE TITLE
Compilation issue wrt databind `UntypedObjectDeserializer` in `master` and `2.19`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#693]
Looks like fix for https://github.com/FasterXML/jackson-databind/issues/4680 (via PR https://github.com/FasterXML/jackson-databind/pull/4684) caused small breakage on Scala module, as per:

https://github.com/FasterXML/jackson-module-scala/actions/runs/11678041619/job/32516901028

and probably just needs explicit cast or something.

Issue was spotted by cascading rebuild. Would be great if this could be done for PRs, but at least there's only 10-15 minute delay now, instead of days or weeks to find these issues previously.

**Comment by pjfanning** [comment]
I committed fixes on both branches

**Comment by cowtowncoder** [comment]
Thank you!
