### ISSUE TITLE
Update 3.0 (master) build, CI to use Java 17 baseline

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-scala#696]
As per https://github.com/FasterXML/jackson-databind/issues/4820 I have updated other modules to use Java/JDK 17 as the baseline (pending discussion on whether even later Java version might be used). If Scala module has not yet been upgraded, let's do that (since core components' published versions are built for Java 17 target).

**Comment by pjfanning** [comment]
changes are made
