### ISSUE TITLE
Fail to deserialize `@JsonUnwrapped` properties passed via `@JsonCreator`

### ISSUE THREAD

**Issue by yunglin** [FasterXML/jackson-module-scala#90]
I am trying to use @JsonUnwrapped to make a flatten json object into more structure scala object. However, jackson will throw `java.lang.IllegalStateException: Method should never be called on a com.fasterxml.jackson.databind.deser.CreatorProperty`

I wrote a test case for this issue and tested on 2.2.2 release and 2.3.0-SNAPSHOT, and neither of them can pass the test.

```
import com.fasterxml.jackson.annotation.{JsonUnwrapped, JsonProperty, JsonCreator}
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.scalatest.testng.TestNGSuite
import org.testng.annotations.Test

/**
 */

case class Person @JsonCreator() (
    @JsonProperty("name") name: String,
    @JsonUnwrapped location: Address,
    @JsonProperty("alias") alias: Option[String] = None
)

case class Address @JsonCreator() (
    @JsonProperty("address1") address1: Option[String] = None,
    @JsonProperty("city") city: Option[String] = None,
    @JsonProperty("state") state:Option[String] = None
 )

class JsonCreatorTest extends TestNGSuite {

  @Test
  def testReadWriteJson {
    val person = new Person("MyName", Address(Some("main street"), Some("springfield")))
    val mapper = new ObjectMapper()
    mapper.registerModule(new DefaultScalaModule)

    val json = mapper.writeValueAsString(person)
    println(json)
    val obj = mapper.readValue(json, classOf[Person])

    assert(obj === person)
  }
}
```

**Comment by mbknor** [comment]
I also hit this issue today... Now that FasterXML/jackson-databind#265 is fixed, maybe we can get this to work?

**Comment by mbknor** [comment]
I now see that scala has the same problem as Kotlin and that https://github.com/FasterXML/jackson-databind/issues/1467 must be fixed..

**Comment by zt1983811** [comment]
I hit this issue today, any update on this as now is 2021 almost 9 years

**Comment by pjfanning** [comment]
I presume this was closed so that discussion can continue on https://github.com/FasterXML/jackson-databind/issues/1467

**Comment by cowtowncoder** [comment]
Yes; this is not Scala-specific as far as I know.
